package com.hz.demo.model;

import java.math.BigDecimal;

/***
 * 通知专家
 */
public class base_speciality_notice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY_NOTICE.ID
     *
     * @mbg.generated Fri Oct 12 14:59:21 CST 2018
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY_NOTICE.TYPE
     *
     * @mbg.generated Fri Oct 12 14:59:21 CST 2018
     */
    private Short type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY_NOTICE.REASON
     *
     * @mbg.generated Fri Oct 12 14:59:21 CST 2018
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY_NOTICE.DIRECTOR
     *
     * @mbg.generated Fri Oct 12 14:59:21 CST 2018
     */
    private Short director;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY_NOTICE.PERSONAL_NUMBER
     *
     * @mbg.generated Fri Oct 12 14:59:21 CST 2018
     */
    private String personalNumber;

    private String groupId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_SPECIALITY_NOTICE.ID
     *
     * @return the value of BASE_SPECIALITY_NOTICE.ID
     *
     * @mbg.generated Fri Oct 12 14:59:21 CST 2018
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_SPECIALITY_NOTICE.ID
     *
     * @param id the value for BASE_SPECIALITY_NOTICE.ID
     *
     * @mbg.generated Fri Oct 12 14:59:21 CST 2018
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_SPECIALITY_NOTICE.TYPE
     *
     * @return the value of BASE_SPECIALITY_NOTICE.TYPE
     *
     * @mbg.generated Fri Oct 12 14:59:21 CST 2018
     */
    public Short getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_SPECIALITY_NOTICE.TYPE
     *
     * @param type the value for BASE_SPECIALITY_NOTICE.TYPE
     *
     * @mbg.generated Fri Oct 12 14:59:21 CST 2018
     */
    public void setType(Short type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_SPECIALITY_NOTICE.REASON
     *
     * @return the value of BASE_SPECIALITY_NOTICE.REASON
     *
     * @mbg.generated Fri Oct 12 14:59:21 CST 2018
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_SPECIALITY_NOTICE.REASON
     *
     * @param reason the value for BASE_SPECIALITY_NOTICE.REASON
     *
     * @mbg.generated Fri Oct 12 14:59:21 CST 2018
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_SPECIALITY_NOTICE.DIRECTOR
     *
     * @return the value of BASE_SPECIALITY_NOTICE.DIRECTOR
     *
     * @mbg.generated Fri Oct 12 14:59:21 CST 2018
     */
    public Short getDirector() {
        return director;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_SPECIALITY_NOTICE.DIRECTOR
     *
     * @param director the value for BASE_SPECIALITY_NOTICE.DIRECTOR
     *
     * @mbg.generated Fri Oct 12 14:59:21 CST 2018
     */
    public void setDirector(Short director) {
        this.director = director;
    }




    public String getPersonalNumber() {
        return personalNumber;
    }
    public void setPersonalNumber(String personalNumber) {
        this.personalNumber = personalNumber == null ? null : personalNumber.trim();
    }
    public String getGroupId() {
        return groupId;
    }
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }
}