package com.hz.demo.model;

public class base_series_professial {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SERIES_PROFESSIAL.ID
     *
     * @mbg.generated Mon Oct 29 11:19:37 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SERIES_PROFESSIAL.REVIEW_SERIES
     *
     * @mbg.generated Mon Oct 29 11:19:37 CST 2018
     */
    private String reviewSeries;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SERIES_PROFESSIAL.PROFESSIAL_CODE
     *
     * @mbg.generated Mon Oct 29 11:19:37 CST 2018
     */
    private String professialCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SERIES_PROFESSIAL.BACK1
     *
     * @mbg.generated Mon Oct 29 11:19:37 CST 2018
     */
    private String back1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SERIES_PROFESSIAL.BACK2
     *
     * @mbg.generated Mon Oct 29 11:19:37 CST 2018
     */
    private String back2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SERIES_PROFESSIAL.BACK3
     *
     * @mbg.generated Mon Oct 29 11:19:37 CST 2018
     */
    private String back3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SERIES_PROFESSIAL.PROFESSIAL_NAME
     *
     * @mbg.generated Mon Oct 29 11:19:37 CST 2018
     */
    private String professialName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SERIES_PROFESSIAL.STATE
     *
     * @mbg.generated Mon Oct 29 11:19:37 CST 2018
     */
    private Short state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_SERIES_PROFESSIAL.ID
     *
     * @return the value of BASE_SERIES_PROFESSIAL.ID
     *
     * @mbg.generated Mon Oct 29 11:19:37 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_SERIES_PROFESSIAL.ID
     *
     * @param id the value for BASE_SERIES_PROFESSIAL.ID
     *
     * @mbg.generated Mon Oct 29 11:19:37 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_SERIES_PROFESSIAL.REVIEW_SERIES
     *
     * @return the value of BASE_SERIES_PROFESSIAL.REVIEW_SERIES
     *
     * @mbg.generated Mon Oct 29 11:19:37 CST 2018
     */
    public String getReviewSeries() {
        return reviewSeries;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_SERIES_PROFESSIAL.REVIEW_SERIES
     *
     * @param reviewSeries the value for BASE_SERIES_PROFESSIAL.REVIEW_SERIES
     *
     * @mbg.generated Mon Oct 29 11:19:37 CST 2018
     */
    public void setReviewSeries(String reviewSeries) {
        this.reviewSeries = reviewSeries == null ? null : reviewSeries.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_SERIES_PROFESSIAL.PROFESSIAL_CODE
     *
     * @return the value of BASE_SERIES_PROFESSIAL.PROFESSIAL_CODE
     *
     * @mbg.generated Mon Oct 29 11:19:37 CST 2018
     */
    public String getProfessialCode() {
        return professialCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_SERIES_PROFESSIAL.PROFESSIAL_CODE
     *
     * @param professialCode the value for BASE_SERIES_PROFESSIAL.PROFESSIAL_CODE
     *
     * @mbg.generated Mon Oct 29 11:19:37 CST 2018
     */
    public void setProfessialCode(String professialCode) {
        this.professialCode = professialCode == null ? null : professialCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_SERIES_PROFESSIAL.BACK1
     *
     * @return the value of BASE_SERIES_PROFESSIAL.BACK1
     *
     * @mbg.generated Mon Oct 29 11:19:37 CST 2018
     */
    public String getBack1() {
        return back1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_SERIES_PROFESSIAL.BACK1
     *
     * @param back1 the value for BASE_SERIES_PROFESSIAL.BACK1
     *
     * @mbg.generated Mon Oct 29 11:19:37 CST 2018
     */
    public void setBack1(String back1) {
        this.back1 = back1 == null ? null : back1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_SERIES_PROFESSIAL.BACK2
     *
     * @return the value of BASE_SERIES_PROFESSIAL.BACK2
     *
     * @mbg.generated Mon Oct 29 11:19:37 CST 2018
     */
    public String getBack2() {
        return back2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_SERIES_PROFESSIAL.BACK2
     *
     * @param back2 the value for BASE_SERIES_PROFESSIAL.BACK2
     *
     * @mbg.generated Mon Oct 29 11:19:37 CST 2018
     */
    public void setBack2(String back2) {
        this.back2 = back2 == null ? null : back2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_SERIES_PROFESSIAL.BACK3
     *
     * @return the value of BASE_SERIES_PROFESSIAL.BACK3
     *
     * @mbg.generated Mon Oct 29 11:19:37 CST 2018
     */
    public String getBack3() {
        return back3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_SERIES_PROFESSIAL.BACK3
     *
     * @param back3 the value for BASE_SERIES_PROFESSIAL.BACK3
     *
     * @mbg.generated Mon Oct 29 11:19:37 CST 2018
     */
    public void setBack3(String back3) {
        this.back3 = back3 == null ? null : back3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_SERIES_PROFESSIAL.PROFESSIAL_NAME
     *
     * @return the value of BASE_SERIES_PROFESSIAL.PROFESSIAL_NAME
     *
     * @mbg.generated Mon Oct 29 11:19:37 CST 2018
     */
    public String getProfessialName() {
        return professialName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_SERIES_PROFESSIAL.PROFESSIAL_NAME
     *
     * @param professialName the value for BASE_SERIES_PROFESSIAL.PROFESSIAL_NAME
     *
     * @mbg.generated Mon Oct 29 11:19:37 CST 2018
     */
    public void setProfessialName(String professialName) {
        this.professialName = professialName == null ? null : professialName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_SERIES_PROFESSIAL.STATE
     *
     * @return the value of BASE_SERIES_PROFESSIAL.STATE
     *
     * @mbg.generated Mon Oct 29 11:19:37 CST 2018
     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_SERIES_PROFESSIAL.STATE
     *
     * @param state the value for BASE_SERIES_PROFESSIAL.STATE
     *
     * @mbg.generated Mon Oct 29 11:19:37 CST 2018
     */
    public void setState(Short state) {
        this.state = state;
    }
}