package com.hz.demo.model;

import java.math.BigDecimal;
import java.util.Date;

public class base_judging {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_JUDGING.ID
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_JUDGING.JUDGING_CODE
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    private String judgingCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_JUDGING.JUDGING_NAME
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    private String judgingName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_JUDGING.REVIEW_JURISDICTION
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    private String reviewJurisdiction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_JUDGING.REVIEW_SCOPE
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    private String reviewScope;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_JUDGING.BUILD_UNIT
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    private String buildUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_JUDGING.MANAGE_UNIT
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    private String manageUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_JUDGING.LINKMAN
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    private String linkman;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_JUDGING.PHONE
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_JUDGING.EMAIL
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_JUDGING.POSTAL_CODE
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    private String postalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_JUDGING.FAX
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    private String fax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_JUDGING.JURY_LEVEL
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    private String juryLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_JUDGING.RECORD_DATE
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    private Date recordDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_JUDGING.ADDTIME
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    private Date addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_JUDGING.ADDUSERID
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    private String adduserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_JUDGING.STATE
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    private BigDecimal state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_JUDGING.BACK1
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    private String back1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_JUDGING.BACK2
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    private String back2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_JUDGING.BACK3
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    private String back3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_JUDGING.ID
     *
     * @return the value of BASE_JUDGING.ID
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_JUDGING.ID
     *
     * @param id the value for BASE_JUDGING.ID
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_JUDGING.JUDGING_CODE
     *
     * @return the value of BASE_JUDGING.JUDGING_CODE
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    public String getJudgingCode() {
        return judgingCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_JUDGING.JUDGING_CODE
     *
     * @param judgingCode the value for BASE_JUDGING.JUDGING_CODE
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    public void setJudgingCode(String judgingCode) {
        this.judgingCode = judgingCode == null ? null : judgingCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_JUDGING.JUDGING_NAME
     *
     * @return the value of BASE_JUDGING.JUDGING_NAME
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    public String getJudgingName() {
        return judgingName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_JUDGING.JUDGING_NAME
     *
     * @param judgingName the value for BASE_JUDGING.JUDGING_NAME
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    public void setJudgingName(String judgingName) {
        this.judgingName = judgingName == null ? null : judgingName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_JUDGING.REVIEW_JURISDICTION
     *
     * @return the value of BASE_JUDGING.REVIEW_JURISDICTION
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    public String getReviewJurisdiction() {
        return reviewJurisdiction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_JUDGING.REVIEW_JURISDICTION
     *
     * @param reviewJurisdiction the value for BASE_JUDGING.REVIEW_JURISDICTION
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    public void setReviewJurisdiction(String reviewJurisdiction) {
        this.reviewJurisdiction = reviewJurisdiction == null ? null : reviewJurisdiction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_JUDGING.REVIEW_SCOPE
     *
     * @return the value of BASE_JUDGING.REVIEW_SCOPE
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    public String getReviewScope() {
        return reviewScope;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_JUDGING.REVIEW_SCOPE
     *
     * @param reviewScope the value for BASE_JUDGING.REVIEW_SCOPE
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    public void setReviewScope(String reviewScope) {
        this.reviewScope = reviewScope == null ? null : reviewScope.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_JUDGING.BUILD_UNIT
     *
     * @return the value of BASE_JUDGING.BUILD_UNIT
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    public String getBuildUnit() {
        return buildUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_JUDGING.BUILD_UNIT
     *
     * @param buildUnit the value for BASE_JUDGING.BUILD_UNIT
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    public void setBuildUnit(String buildUnit) {
        this.buildUnit = buildUnit == null ? null : buildUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_JUDGING.MANAGE_UNIT
     *
     * @return the value of BASE_JUDGING.MANAGE_UNIT
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    public String getManageUnit() {
        return manageUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_JUDGING.MANAGE_UNIT
     *
     * @param manageUnit the value for BASE_JUDGING.MANAGE_UNIT
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    public void setManageUnit(String manageUnit) {
        this.manageUnit = manageUnit == null ? null : manageUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_JUDGING.LINKMAN
     *
     * @return the value of BASE_JUDGING.LINKMAN
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    public String getLinkman() {
        return linkman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_JUDGING.LINKMAN
     *
     * @param linkman the value for BASE_JUDGING.LINKMAN
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    public void setLinkman(String linkman) {
        this.linkman = linkman == null ? null : linkman.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_JUDGING.PHONE
     *
     * @return the value of BASE_JUDGING.PHONE
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_JUDGING.PHONE
     *
     * @param phone the value for BASE_JUDGING.PHONE
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_JUDGING.EMAIL
     *
     * @return the value of BASE_JUDGING.EMAIL
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_JUDGING.EMAIL
     *
     * @param email the value for BASE_JUDGING.EMAIL
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_JUDGING.POSTAL_CODE
     *
     * @return the value of BASE_JUDGING.POSTAL_CODE
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_JUDGING.POSTAL_CODE
     *
     * @param postalCode the value for BASE_JUDGING.POSTAL_CODE
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode == null ? null : postalCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_JUDGING.FAX
     *
     * @return the value of BASE_JUDGING.FAX
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_JUDGING.FAX
     *
     * @param fax the value for BASE_JUDGING.FAX
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    public void setFax(String fax) {
        this.fax = fax == null ? null : fax.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_JUDGING.JURY_LEVEL
     *
     * @return the value of BASE_JUDGING.JURY_LEVEL
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    public String getJuryLevel() {
        return juryLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_JUDGING.JURY_LEVEL
     *
     * @param juryLevel the value for BASE_JUDGING.JURY_LEVEL
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    public void setJuryLevel(String juryLevel) {
        this.juryLevel = juryLevel == null ? null : juryLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_JUDGING.RECORD_DATE
     *
     * @return the value of BASE_JUDGING.RECORD_DATE
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    public Date getRecordDate() {
        return recordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_JUDGING.RECORD_DATE
     *
     * @param recordDate the value for BASE_JUDGING.RECORD_DATE
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    public void setRecordDate(Date recordDate) {
        this.recordDate = recordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_JUDGING.ADDTIME
     *
     * @return the value of BASE_JUDGING.ADDTIME
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_JUDGING.ADDTIME
     *
     * @param addtime the value for BASE_JUDGING.ADDTIME
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_JUDGING.ADDUSERID
     *
     * @return the value of BASE_JUDGING.ADDUSERID
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    public String getAdduserid() {
        return adduserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_JUDGING.ADDUSERID
     *
     * @param adduserid the value for BASE_JUDGING.ADDUSERID
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    public void setAdduserid(String adduserid) {
        this.adduserid = adduserid == null ? null : adduserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_JUDGING.STATE
     *
     * @return the value of BASE_JUDGING.STATE
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    public BigDecimal getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_JUDGING.STATE
     *
     * @param state the value for BASE_JUDGING.STATE
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    public void setState(BigDecimal state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_JUDGING.BACK1
     *
     * @return the value of BASE_JUDGING.BACK1
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    public String getBack1() {
        return back1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_JUDGING.BACK1
     *
     * @param back1 the value for BASE_JUDGING.BACK1
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    public void setBack1(String back1) {
        this.back1 = back1 == null ? null : back1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_JUDGING.BACK2
     *
     * @return the value of BASE_JUDGING.BACK2
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    public String getBack2() {
        return back2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_JUDGING.BACK2
     *
     * @param back2 the value for BASE_JUDGING.BACK2
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    public void setBack2(String back2) {
        this.back2 = back2 == null ? null : back2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_JUDGING.BACK3
     *
     * @return the value of BASE_JUDGING.BACK3
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    public String getBack3() {
        return back3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_JUDGING.BACK3
     *
     * @param back3 the value for BASE_JUDGING.BACK3
     *
     * @mbg.generated Thu Sep 13 15:09:53 CST 2018
     */
    public void setBack3(String back3) {
        this.back3 = back3 == null ? null : back3.trim();
    }
}