package com.hz.demo.model;

import java.math.BigDecimal;
import java.util.Date;

/***
 * 黑名单
 */
public class base_blacklist {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_BLACKLIST.ID
     *
     * @mbg.generated Thu Oct 18 10:42:57 CST 2018
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_BLACKLIST.PROPOSER_NAME
     *
     * @mbg.generated Thu Oct 18 10:42:57 CST 2018
     */
    private String proposerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_BLACKLIST.ID_CARD_NO
     *
     * @mbg.generated Thu Oct 18 10:42:57 CST 2018
     */
    private String idCardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_BLACKLIST.MOBILEPHONE
     *
     * @mbg.generated Thu Oct 18 10:42:57 CST 2018
     */
    private String mobilephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_BLACKLIST.RELIEVE_DATE
     *
     * @mbg.generated Thu Oct 18 10:42:57 CST 2018
     */
    private Date relieveDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_BLACKLIST.REASON
     *
     * @mbg.generated Thu Oct 18 10:42:57 CST 2018
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_BLACKLIST.ADDTIME
     *
     * @mbg.generated Thu Oct 18 10:42:57 CST 2018
     */
    private Date addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_BLACKLIST.ADDUSERID
     *
     * @mbg.generated Thu Oct 18 10:42:57 CST 2018
     */
    private String adduserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_BLACKLIST.STATE
     *
     * @mbg.generated Thu Oct 18 10:42:57 CST 2018
     */
    private BigDecimal state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_BLACKLIST.UNIT_NAME
     *
     * @mbg.generated Thu Oct 18 10:42:57 CST 2018
     */
    private String unitName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_BLACKLIST.BACK1
     *
     * @mbg.generated Thu Oct 18 10:42:57 CST 2018
     */
    private String back1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_BLACKLIST.BACK2
     *
     * @mbg.generated Thu Oct 18 10:42:57 CST 2018
     */
    private String back2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_BLACKLIST.BACK3
     *
     * @mbg.generated Thu Oct 18 10:42:57 CST 2018
     */
    private String back3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_BLACKLIST.ID
     *
     * @return the value of BASE_BLACKLIST.ID
     *
     * @mbg.generated Thu Oct 18 10:42:57 CST 2018
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_BLACKLIST.ID
     *
     * @param id the value for BASE_BLACKLIST.ID
     *
     * @mbg.generated Thu Oct 18 10:42:57 CST 2018
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_BLACKLIST.PROPOSER_NAME
     *
     * @return the value of BASE_BLACKLIST.PROPOSER_NAME
     *
     * @mbg.generated Thu Oct 18 10:42:57 CST 2018
     */
    public String getProposerName() {
        return proposerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_BLACKLIST.PROPOSER_NAME
     *
     * @param proposerName the value for BASE_BLACKLIST.PROPOSER_NAME
     *
     * @mbg.generated Thu Oct 18 10:42:57 CST 2018
     */
    public void setProposerName(String proposerName) {
        this.proposerName = proposerName == null ? null : proposerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_BLACKLIST.ID_CARD_NO
     *
     * @return the value of BASE_BLACKLIST.ID_CARD_NO
     *
     * @mbg.generated Thu Oct 18 10:42:57 CST 2018
     */
    public String getIdCardNo() {
        return idCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_BLACKLIST.ID_CARD_NO
     *
     * @param idCardNo the value for BASE_BLACKLIST.ID_CARD_NO
     *
     * @mbg.generated Thu Oct 18 10:42:57 CST 2018
     */
    public void setIdCardNo(String idCardNo) {
        this.idCardNo = idCardNo == null ? null : idCardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_BLACKLIST.MOBILEPHONE
     *
     * @return the value of BASE_BLACKLIST.MOBILEPHONE
     *
     * @mbg.generated Thu Oct 18 10:42:57 CST 2018
     */
    public String getMobilephone() {
        return mobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_BLACKLIST.MOBILEPHONE
     *
     * @param mobilephone the value for BASE_BLACKLIST.MOBILEPHONE
     *
     * @mbg.generated Thu Oct 18 10:42:57 CST 2018
     */
    public void setMobilephone(String mobilephone) {
        this.mobilephone = mobilephone == null ? null : mobilephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_BLACKLIST.RELIEVE_DATE
     *
     * @return the value of BASE_BLACKLIST.RELIEVE_DATE
     *
     * @mbg.generated Thu Oct 18 10:42:57 CST 2018
     */
    public Date getRelieveDate() {
        return relieveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_BLACKLIST.RELIEVE_DATE
     *
     * @param relieveDate the value for BASE_BLACKLIST.RELIEVE_DATE
     *
     * @mbg.generated Thu Oct 18 10:42:57 CST 2018
     */
    public void setRelieveDate(Date relieveDate) {
        this.relieveDate = relieveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_BLACKLIST.REASON
     *
     * @return the value of BASE_BLACKLIST.REASON
     *
     * @mbg.generated Thu Oct 18 10:42:57 CST 2018
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_BLACKLIST.REASON
     *
     * @param reason the value for BASE_BLACKLIST.REASON
     *
     * @mbg.generated Thu Oct 18 10:42:57 CST 2018
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_BLACKLIST.ADDTIME
     *
     * @return the value of BASE_BLACKLIST.ADDTIME
     *
     * @mbg.generated Thu Oct 18 10:42:57 CST 2018
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_BLACKLIST.ADDTIME
     *
     * @param addtime the value for BASE_BLACKLIST.ADDTIME
     *
     * @mbg.generated Thu Oct 18 10:42:57 CST 2018
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_BLACKLIST.ADDUSERID
     *
     * @return the value of BASE_BLACKLIST.ADDUSERID
     *
     * @mbg.generated Thu Oct 18 10:42:57 CST 2018
     */
    public String getAdduserid() {
        return adduserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_BLACKLIST.ADDUSERID
     *
     * @param adduserid the value for BASE_BLACKLIST.ADDUSERID
     *
     * @mbg.generated Thu Oct 18 10:42:57 CST 2018
     */
    public void setAdduserid(String adduserid) {
        this.adduserid = adduserid == null ? null : adduserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_BLACKLIST.STATE
     *
     * @return the value of BASE_BLACKLIST.STATE
     *
     * @mbg.generated Thu Oct 18 10:42:57 CST 2018
     */
    public BigDecimal getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_BLACKLIST.STATE
     *
     * @param state the value for BASE_BLACKLIST.STATE
     *
     * @mbg.generated Thu Oct 18 10:42:57 CST 2018
     */
    public void setState(BigDecimal state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_BLACKLIST.UNIT_NAME
     *
     * @return the value of BASE_BLACKLIST.UNIT_NAME
     *
     * @mbg.generated Thu Oct 18 10:42:57 CST 2018
     */
    public String getUnitName() {
        return unitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_BLACKLIST.UNIT_NAME
     *
     * @param unitName the value for BASE_BLACKLIST.UNIT_NAME
     *
     * @mbg.generated Thu Oct 18 10:42:57 CST 2018
     */
    public void setUnitName(String unitName) {
        this.unitName = unitName == null ? null : unitName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_BLACKLIST.BACK1
     *
     * @return the value of BASE_BLACKLIST.BACK1
     *
     * @mbg.generated Thu Oct 18 10:42:57 CST 2018
     */
    public String getBack1() {
        return back1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_BLACKLIST.BACK1
     *
     * @param back1 the value for BASE_BLACKLIST.BACK1
     *
     * @mbg.generated Thu Oct 18 10:42:57 CST 2018
     */
    public void setBack1(String back1) {
        this.back1 = back1 == null ? null : back1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_BLACKLIST.BACK2
     *
     * @return the value of BASE_BLACKLIST.BACK2
     *
     * @mbg.generated Thu Oct 18 10:42:57 CST 2018
     */
    public String getBack2() {
        return back2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_BLACKLIST.BACK2
     *
     * @param back2 the value for BASE_BLACKLIST.BACK2
     *
     * @mbg.generated Thu Oct 18 10:42:57 CST 2018
     */
    public void setBack2(String back2) {
        this.back2 = back2 == null ? null : back2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_BLACKLIST.BACK3
     *
     * @return the value of BASE_BLACKLIST.BACK3
     *
     * @mbg.generated Thu Oct 18 10:42:57 CST 2018
     */
    public String getBack3() {
        return back3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_BLACKLIST.BACK3
     *
     * @param back3 the value for BASE_BLACKLIST.BACK3
     *
     * @mbg.generated Thu Oct 18 10:42:57 CST 2018
     */
    public void setBack3(String back3) {
        this.back3 = back3 == null ? null : back3.trim();
    }
}