package com.hz.demo.model;

import java.math.BigDecimal;
import java.util.Date;

public class base_param_yeardeclare {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_PARAM_YEARDECLARE.ID
     *
     * @mbg.generated Wed Sep 19 14:27:31 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_PARAM_YEARDECLARE.YEARNUMBER
     *
     * @mbg.generated Wed Sep 19 14:27:31 CST 2018
     */
    private String yearnumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_PARAM_YEARDECLARE.REVIEW_SERIES
     *
     * @mbg.generated Wed Sep 19 14:27:31 CST 2018
     */
    private String reviewSeries;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_PARAM_YEARDECLARE.BEGINTIME
     *
     * @mbg.generated Wed Sep 19 14:27:31 CST 2018
     */
    private Date begintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_PARAM_YEARDECLARE.ENDTIME
     *
     * @mbg.generated Wed Sep 19 14:27:31 CST 2018
     */
    private Date endtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_PARAM_YEARDECLARE.START_STATE
     *
     * @mbg.generated Wed Sep 19 14:27:31 CST 2018
     */
    private BigDecimal startState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_PARAM_YEARDECLARE.BACK1
     *
     * @mbg.generated Wed Sep 19 14:27:31 CST 2018
     */
    private String back1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_PARAM_YEARDECLARE.BACK2
     *
     * @mbg.generated Wed Sep 19 14:27:31 CST 2018
     */
    private String back2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_PARAM_YEARDECLARE.BACK3
     *
     * @mbg.generated Wed Sep 19 14:27:31 CST 2018
     */
    private String back3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_PARAM_YEARDECLARE.ID
     *
     * @return the value of BASE_PARAM_YEARDECLARE.ID
     *
     * @mbg.generated Wed Sep 19 14:27:31 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_PARAM_YEARDECLARE.ID
     *
     * @param id the value for BASE_PARAM_YEARDECLARE.ID
     *
     * @mbg.generated Wed Sep 19 14:27:31 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_PARAM_YEARDECLARE.YEARNUMBER
     *
     * @return the value of BASE_PARAM_YEARDECLARE.YEARNUMBER
     *
     * @mbg.generated Wed Sep 19 14:27:31 CST 2018
     */
    public String getYearnumber() {
        return yearnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_PARAM_YEARDECLARE.YEARNUMBER
     *
     * @param yearnumber the value for BASE_PARAM_YEARDECLARE.YEARNUMBER
     *
     * @mbg.generated Wed Sep 19 14:27:31 CST 2018
     */
    public void setYearnumber(String yearnumber) {
        this.yearnumber = yearnumber == null ? null : yearnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_PARAM_YEARDECLARE.REVIEW_SERIES
     *
     * @return the value of BASE_PARAM_YEARDECLARE.REVIEW_SERIES
     *
     * @mbg.generated Wed Sep 19 14:27:31 CST 2018
     */
    public String getReviewSeries() {
        return reviewSeries;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_PARAM_YEARDECLARE.REVIEW_SERIES
     *
     * @param reviewSeries the value for BASE_PARAM_YEARDECLARE.REVIEW_SERIES
     *
     * @mbg.generated Wed Sep 19 14:27:31 CST 2018
     */
    public void setReviewSeries(String reviewSeries) {
        this.reviewSeries = reviewSeries == null ? null : reviewSeries.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_PARAM_YEARDECLARE.BEGINTIME
     *
     * @return the value of BASE_PARAM_YEARDECLARE.BEGINTIME
     *
     * @mbg.generated Wed Sep 19 14:27:31 CST 2018
     */
    public Date getBegintime() {
        return begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_PARAM_YEARDECLARE.BEGINTIME
     *
     * @param begintime the value for BASE_PARAM_YEARDECLARE.BEGINTIME
     *
     * @mbg.generated Wed Sep 19 14:27:31 CST 2018
     */
    public void setBegintime(Date begintime) {
        this.begintime = begintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_PARAM_YEARDECLARE.ENDTIME
     *
     * @return the value of BASE_PARAM_YEARDECLARE.ENDTIME
     *
     * @mbg.generated Wed Sep 19 14:27:31 CST 2018
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_PARAM_YEARDECLARE.ENDTIME
     *
     * @param endtime the value for BASE_PARAM_YEARDECLARE.ENDTIME
     *
     * @mbg.generated Wed Sep 19 14:27:31 CST 2018
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_PARAM_YEARDECLARE.START_STATE
     *
     * @return the value of BASE_PARAM_YEARDECLARE.START_STATE
     *
     * @mbg.generated Wed Sep 19 14:27:31 CST 2018
     */
    public BigDecimal getStartState() {
        return startState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_PARAM_YEARDECLARE.START_STATE
     *
     * @param startState the value for BASE_PARAM_YEARDECLARE.START_STATE
     *
     * @mbg.generated Wed Sep 19 14:27:31 CST 2018
     */
    public void setStartState(BigDecimal startState) {
        this.startState = startState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_PARAM_YEARDECLARE.BACK1
     *
     * @return the value of BASE_PARAM_YEARDECLARE.BACK1
     *
     * @mbg.generated Wed Sep 19 14:27:31 CST 2018
     */
    public String getBack1() {
        return back1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_PARAM_YEARDECLARE.BACK1
     *
     * @param back1 the value for BASE_PARAM_YEARDECLARE.BACK1
     *
     * @mbg.generated Wed Sep 19 14:27:31 CST 2018
     */
    public void setBack1(String back1) {
        this.back1 = back1 == null ? null : back1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_PARAM_YEARDECLARE.BACK2
     *
     * @return the value of BASE_PARAM_YEARDECLARE.BACK2
     *
     * @mbg.generated Wed Sep 19 14:27:31 CST 2018
     */
    public String getBack2() {
        return back2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_PARAM_YEARDECLARE.BACK2
     *
     * @param back2 the value for BASE_PARAM_YEARDECLARE.BACK2
     *
     * @mbg.generated Wed Sep 19 14:27:31 CST 2018
     */
    public void setBack2(String back2) {
        this.back2 = back2 == null ? null : back2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_PARAM_YEARDECLARE.BACK3
     *
     * @return the value of BASE_PARAM_YEARDECLARE.BACK3
     *
     * @mbg.generated Wed Sep 19 14:27:31 CST 2018
     */
    public String getBack3() {
        return back3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_PARAM_YEARDECLARE.BACK3
     *
     * @param back3 the value for BASE_PARAM_YEARDECLARE.BACK3
     *
     * @mbg.generated Wed Sep 19 14:27:31 CST 2018
     */
    public void setBack3(String back3) {
        this.back3 = back3 == null ? null : back3.trim();
    }
}