package com.hz.demo.model;

import java.math.BigDecimal;

public class base_param_review {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_PARAM_REVIEW.ID
     *
     * @mbg.generated Mon Sep 17 16:49:37 CST 2018
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_PARAM_REVIEW.JUDGING_CODE
     *
     * @mbg.generated Mon Sep 17 16:49:37 CST 2018
     */
    private String judgingCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_PARAM_REVIEW.ZG
     *
     * @mbg.generated Mon Sep 17 16:49:37 CST 2018
     */
    private BigDecimal zg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_PARAM_REVIEW.FG
     *
     * @mbg.generated Mon Sep 17 16:49:37 CST 2018
     */
    private BigDecimal fg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_PARAM_REVIEW.ZJ
     *
     * @mbg.generated Mon Sep 17 16:49:37 CST 2018
     */
    private BigDecimal zj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_PARAM_REVIEW.BACK1
     *
     * @mbg.generated Mon Sep 17 16:49:37 CST 2018
     */
    private String back1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_PARAM_REVIEW.BACK2
     *
     * @mbg.generated Mon Sep 17 16:49:37 CST 2018
     */
    private String back2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_PARAM_REVIEW.BACK3
     *
     * @mbg.generated Mon Sep 17 16:49:37 CST 2018
     */
    private String back3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_PARAM_REVIEW.ID
     *
     * @return the value of BASE_PARAM_REVIEW.ID
     *
     * @mbg.generated Mon Sep 17 16:49:37 CST 2018
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_PARAM_REVIEW.ID
     *
     * @param id the value for BASE_PARAM_REVIEW.ID
     *
     * @mbg.generated Mon Sep 17 16:49:37 CST 2018
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_PARAM_REVIEW.JUDGING_CODE
     *
     * @return the value of BASE_PARAM_REVIEW.JUDGING_CODE
     *
     * @mbg.generated Mon Sep 17 16:49:37 CST 2018
     */
    public String getJudgingCode() {
        return judgingCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_PARAM_REVIEW.JUDGING_CODE
     *
     * @param judgingCode the value for BASE_PARAM_REVIEW.JUDGING_CODE
     *
     * @mbg.generated Mon Sep 17 16:49:37 CST 2018
     */
    public void setJudgingCode(String judgingCode) {
        this.judgingCode = judgingCode == null ? null : judgingCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_PARAM_REVIEW.ZG
     *
     * @return the value of BASE_PARAM_REVIEW.ZG
     *
     * @mbg.generated Mon Sep 17 16:49:37 CST 2018
     */
    public BigDecimal getZg() {
        return zg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_PARAM_REVIEW.ZG
     *
     * @param zg the value for BASE_PARAM_REVIEW.ZG
     *
     * @mbg.generated Mon Sep 17 16:49:37 CST 2018
     */
    public void setZg(BigDecimal zg) {
        this.zg = zg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_PARAM_REVIEW.FG
     *
     * @return the value of BASE_PARAM_REVIEW.FG
     *
     * @mbg.generated Mon Sep 17 16:49:37 CST 2018
     */
    public BigDecimal getFg() {
        return fg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_PARAM_REVIEW.FG
     *
     * @param fg the value for BASE_PARAM_REVIEW.FG
     *
     * @mbg.generated Mon Sep 17 16:49:37 CST 2018
     */
    public void setFg(BigDecimal fg) {
        this.fg = fg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_PARAM_REVIEW.ZJ
     *
     * @return the value of BASE_PARAM_REVIEW.ZJ
     *
     * @mbg.generated Mon Sep 17 16:49:37 CST 2018
     */
    public BigDecimal getZj() {
        return zj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_PARAM_REVIEW.ZJ
     *
     * @param zj the value for BASE_PARAM_REVIEW.ZJ
     *
     * @mbg.generated Mon Sep 17 16:49:37 CST 2018
     */
    public void setZj(BigDecimal zj) {
        this.zj = zj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_PARAM_REVIEW.BACK1
     *
     * @return the value of BASE_PARAM_REVIEW.BACK1
     *
     * @mbg.generated Mon Sep 17 16:49:37 CST 2018
     */
    public String getBack1() {
        return back1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_PARAM_REVIEW.BACK1
     *
     * @param back1 the value for BASE_PARAM_REVIEW.BACK1
     *
     * @mbg.generated Mon Sep 17 16:49:37 CST 2018
     */
    public void setBack1(String back1) {
        this.back1 = back1 == null ? null : back1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_PARAM_REVIEW.BACK2
     *
     * @return the value of BASE_PARAM_REVIEW.BACK2
     *
     * @mbg.generated Mon Sep 17 16:49:37 CST 2018
     */
    public String getBack2() {
        return back2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_PARAM_REVIEW.BACK2
     *
     * @param back2 the value for BASE_PARAM_REVIEW.BACK2
     *
     * @mbg.generated Mon Sep 17 16:49:37 CST 2018
     */
    public void setBack2(String back2) {
        this.back2 = back2 == null ? null : back2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_PARAM_REVIEW.BACK3
     *
     * @return the value of BASE_PARAM_REVIEW.BACK3
     *
     * @mbg.generated Mon Sep 17 16:49:37 CST 2018
     */
    public String getBack3() {
        return back3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_PARAM_REVIEW.BACK3
     *
     * @param back3 the value for BASE_PARAM_REVIEW.BACK3
     *
     * @mbg.generated Mon Sep 17 16:49:37 CST 2018
     */
    public void setBack3(String back3) {
        this.back3 = back3 == null ? null : back3.trim();
    }
}