package com.hz.demo.model;

import java.math.BigDecimal;
import java.util.Date;

public class base_engage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_ENGAGE.ID
     *
     * @mbg.generated Mon Sep 17 17:35:31 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_ENGAGE.JUDGING_ID
     *
     * @mbg.generated Mon Sep 17 17:35:31 CST 2018
     */
    private String judgingId;
    private String judgingCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_ENGAGE.SPECIALITY_ID
     *
     * @mbg.generated Mon Sep 17 17:35:31 CST 2018
     */
    private String specialityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_ENGAGE.JURY_DUTY
     *
     * @mbg.generated Mon Sep 17 17:35:31 CST 2018
     */
    private String juryDuty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_ENGAGE.AREACODE
     *
     * @mbg.generated Mon Sep 17 17:35:31 CST 2018
     */
    private String areacode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_ENGAGE.BEGIN_DATE
     *
     * @mbg.generated Mon Sep 17 17:35:31 CST 2018
     */
    private Date beginDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_ENGAGE.END_DATE
     *
     * @mbg.generated Mon Sep 17 17:35:31 CST 2018
     */
    private Date endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_ENGAGE.ADDTIME
     *
     * @mbg.generated Mon Sep 17 17:35:31 CST 2018
     */
    private Date addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_ENGAGE.ADDUSERID
     *
     * @mbg.generated Mon Sep 17 17:35:31 CST 2018
     */
    private String adduserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_ENGAGE.STATE
     *
     * @mbg.generated Mon Sep 17 17:35:31 CST 2018
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_ENGAGE.BACK1
     *
     * @mbg.generated Mon Sep 17 17:35:31 CST 2018
     */
    private String back1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_ENGAGE.BACK2
     *
     * @mbg.generated Mon Sep 17 17:35:31 CST 2018
     */
    private String back2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_ENGAGE.BACK3
     *
     * @mbg.generated Mon Sep 17 17:35:31 CST 2018
     */
    private String back3;

    private String type;

    private String reason;
    private base_speciality baseSpeciality;

    @Override
    public String toString() {
        return "base_engage{" +
                "id=" + id +
                ", judgingId='" + judgingId + '\'' +
                ", specialityId='" + specialityId + '\'' +
                ", juryDuty='" + juryDuty + '\'' +
                ", areacode='" + areacode + '\'' +
                ", beginDate=" + beginDate +
                ", endDate=" + endDate +
                ", addtime=" + addtime +
                ", adduserid='" + adduserid + '\'' +
                ", state=" + state +
                ", baseSpeciality=" + baseSpeciality +
                ", judgingCode=" + judgingCode +
                '}';
    }


    public String getJudgingCode() {return judgingCode; }
    public void setJudgingCode(String judgingCode) {
        this.judgingCode = judgingCode;
    }

    public String getType() {return type; }
    public void setType(String type) {
        this.type = type;
    }

    public String getReason() {
        return reason;
    }
    public void setReason(String reason) {
        this.reason = reason;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getJudgingId() {
        return judgingId;
    }

    public void setJudgingId(String judgingId) {
        this.judgingId = judgingId;
    }

    public String getSpecialityId() {
        return specialityId;
    }

    public void setSpecialityId(String specialityId) {
        this.specialityId = specialityId;
    }

    public String getJuryDuty() {
        return juryDuty;
    }

    public void setJuryDuty(String juryDuty) {
        this.juryDuty = juryDuty;
    }

    public String getAreacode() {
        return areacode;
    }

    public void setAreacode(String areacode) {
        this.areacode = areacode;
    }

    public Date getBeginDate() {
        return beginDate;
    }

    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }

    public Date getEndDate() {
        return endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public Date getAddtime() {
        return addtime;
    }

    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    public String getAdduserid() {
        return adduserid;
    }

    public void setAdduserid(String adduserid) {
        this.adduserid = adduserid;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public String getBack1() {
        return back1;
    }

    public void setBack1(String back1) {
        this.back1 = back1;
    }

    public String getBack2() {
        return back2;
    }

    public void setBack2(String back2) {
        this.back2 = back2;
    }

    public String getBack3() {
        return back3;
    }

    public void setBack3(String back3) {
        this.back3 = back3;
    }

    public base_speciality getBaseSpeciality() {
        return baseSpeciality;
    }

    public void setBaseSpeciality(base_speciality baseSpeciality) {
        this.baseSpeciality = baseSpeciality;
    }

    public base_engage() {

    }

    public base_engage(Integer id, String judgingId, String specialityId, String juryDuty, String areacode, Date beginDate, Date endDate, Date addtime, String adduserid, Integer state, String back1, String back2, String back3, base_speciality baseSpeciality,String judgingCode) {

        this.id = id;
        this.judgingId = judgingId;
        this.specialityId = specialityId;
        this.juryDuty = juryDuty;
        this.areacode = areacode;
        this.beginDate = beginDate;
        this.endDate = endDate;
        this.addtime = addtime;
        this.adduserid = adduserid;
        this.state = state;
        this.back1 = back1;
        this.back2 = back2;
        this.back3 = back3;
        this.baseSpeciality = baseSpeciality;
        this.judgingCode=judgingCode;
    }
}