package com.hz.demo.model;

import java.math.BigDecimal;
import java.util.Date;

public class base_speciality {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY.ID
     *
     * @mbg.generated Thu Sep 13 11:39:35 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY.PERSONAL_NUMBER
     *
     * @mbg.generated Thu Sep 13 11:39:35 CST 2018
     */
    private String personalNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY.ADMINISTRATIVE_DUTY_LEVEL
     *
     * @mbg.generated Thu Sep 13 11:39:35 CST 2018
     */
    private String administrativeDutyLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY.PROFESSIAL_DUTY_LEVEL
     *
     * @mbg.generated Thu Sep 13 11:39:35 CST 2018
     */
    private String professialDutyLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY.PROFESSIAL_LEVEL
     *
     * @mbg.generated Thu Sep 13 11:39:35 CST 2018
     */
    private String professialLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY.PROFESSIAL
     *
     * @mbg.generated Thu Sep 13 11:39:35 CST 2018
     */
    private String professial;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY.JOB_YEAR
     *
     * @mbg.generated Thu Sep 13 11:39:35 CST 2018
     */
    private String jobYear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY.PERFORMANCE
     *
     * @mbg.generated Thu Sep 13 11:39:35 CST 2018
     */
    private String performance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY.EDUCATION
     *
     * @mbg.generated Thu Sep 13 11:39:35 CST 2018
     */
    private String education;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY.DEGREE
     *
     * @mbg.generated Thu Sep 13 11:39:35 CST 2018
     */
    private String degree;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY.NOWUNIT
     *
     * @mbg.generated Thu Sep 13 11:39:35 CST 2018
     */
    private String nowunit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY.AREACODE
     *
     * @mbg.generated Thu Sep 13 11:39:35 CST 2018
     */
    private String areacode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY.SPECIALITY_NAME
     *
     * @mbg.generated Thu Sep 13 11:39:35 CST 2018
     */
    private String specialityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY.SEX
     *
     * @mbg.generated Thu Sep 13 11:39:35 CST 2018
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY.ID_CARD_NO
     *
     * @mbg.generated Thu Sep 13 11:39:35 CST 2018
     */
    private String idCardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY.BIRTHDATE
     *
     * @mbg.generated Thu Sep 13 11:39:35 CST 2018
     */
    private Date birthdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY.GRADUATE_SCHOOL
     *
     * @mbg.generated Thu Sep 13 11:39:35 CST 2018
     */
    private String graduateSchool;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY.GRADUATE_DATE
     *
     * @mbg.generated Thu Sep 13 11:39:35 CST 2018
     */
    private Date graduateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY.MOBILEPHONE
     *
     * @mbg.generated Thu Sep 13 11:39:35 CST 2018
     */
    private String mobilephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY.TEL
     *
     * @mbg.generated Thu Sep 13 11:39:35 CST 2018
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY.POSTAL_ADDRESS
     *
     * @mbg.generated Thu Sep 13 11:39:35 CST 2018
     */
    private String postalAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY.POSTAL_CODE
     *
     * @mbg.generated Thu Sep 13 11:39:35 CST 2018
     */
    private String postalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY.EMAIL
     *
     * @mbg.generated Thu Sep 13 11:39:35 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY.PRESENTATION
     *
     * @mbg.generated Thu Sep 13 11:39:35 CST 2018
     */
    private String presentation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY.ADDTIME
     *
     * @mbg.generated Thu Sep 13 11:39:35 CST 2018
     */
    private Date addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY.ADDUSERID
     *
     * @mbg.generated Thu Sep 13 11:39:35 CST 2018
     */
    private String adduserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY.STATE
     *
     * @mbg.generated Thu Sep 13 11:39:35 CST 2018
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY.BACK1
     *
     * @mbg.generated Thu Sep 13 11:39:35 CST 2018
     */
    private String back1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY.BACK2
     *
     * @mbg.generated Thu Sep 13 11:39:35 CST 2018
     */
    private String back2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY.BACK3
     *
     * @mbg.generated Thu Sep 13 11:39:35 CST 2018
     */
    private String back3;
    private String type;
    private String reason;
    private String groupId;
    private String bspid;
    private base_engage baseEngage;

    private String recommendSeries;

    private String recommendMajor;

    private Integer isRandom;

    @Override
    public String toString() {
        return "base_speciality{" +
                "id=" + id +
                ", personalNumber='" + personalNumber + '\'' +
                ", administrativeDutyLevel='" + administrativeDutyLevel + '\'' +
                ", professialDutyLevel='" + professialDutyLevel + '\'' +
                ", professialLevel='" + professialLevel + '\'' +
                ", professial='" + professial + '\'' +
                ", jobYear='" + jobYear + '\'' +
                ", performance='" + performance + '\'' +
                ", education='" + education + '\'' +
                ", degree='" + degree + '\'' +
                ", nowunit='" + nowunit + '\'' +
                ", areacode='" + areacode + '\'' +
                ", specialityName='" + specialityName + '\'' +
                ", sex='" + sex + '\'' +
                ", idCardNo='" + idCardNo + '\'' +
                ", birthdate=" + birthdate +
                ", graduateSchool='" + graduateSchool + '\'' +
                ", graduateDate=" + graduateDate +
                ", mobilephone='" + mobilephone + '\'' +
                ", tel='" + tel + '\'' +
                ", postalAddress='" + postalAddress + '\'' +
                ", postalCode='" + postalCode + '\'' +
                ", email='" + email + '\'' +
                ", presentation='" + presentation + '\'' +
                ", addtime=" + addtime +
                ", adduserid='" + adduserid + '\'' +
                ", state=" + state +
                ", back1='" + back1 + '\'' +
                ", back2='" + back2 + '\'' +
                ", back3='" + back3 + '\'' +
                ", baseEngage=" + baseEngage +
                ", recommendSeries='" + recommendSeries + '\'' +
                ", recommendMajor='" + recommendMajor + '\'' +
                ", isRandom=" + isRandom +
                '}';
    }

    public String getBspid() {  return bspid; }

    public void setBspid(String bspid) {
        this.bspid = bspid;
    }
    public String getType() {  return type; }

    public void setType(String type) {
        this.type = type;
    }
    public String getGroupId() {  return groupId; }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getPersonalNumber() {
        return personalNumber;
    }

    public void setPersonalNumber(String personalNumber) {
        this.personalNumber = personalNumber;
    }

    public String getAdministrativeDutyLevel() {
        return administrativeDutyLevel;
    }

    public void setAdministrativeDutyLevel(String administrativeDutyLevel) {
        this.administrativeDutyLevel = administrativeDutyLevel;
    }

    public String getProfessialDutyLevel() {
        return professialDutyLevel;
    }

    public void setProfessialDutyLevel(String professialDutyLevel) {
        this.professialDutyLevel = professialDutyLevel;
    }

    public String getProfessialLevel() {
        return professialLevel;
    }

    public void setProfessialLevel(String professialLevel) {
        this.professialLevel = professialLevel;
    }

    public String getProfessial() {
        return professial;
    }

    public void setProfessial(String professial) {
        this.professial = professial;
    }

    public String getJobYear() {
        return jobYear;
    }

    public void setJobYear(String jobYear) {
        this.jobYear = jobYear;
    }

    public String getPerformance() {
        return performance;
    }

    public void setPerformance(String performance) {
        this.performance = performance;
    }

    public String getEducation() {
        return education;
    }

    public void setEducation(String education) {
        this.education = education;
    }

    public String getDegree() {
        return degree;
    }

    public void setDegree(String degree) {
        this.degree = degree;
    }

    public String getNowunit() {
        return nowunit;
    }

    public void setNowunit(String nowunit) {
        this.nowunit = nowunit;
    }

    public String getAreacode() {
        return areacode;
    }

    public void setAreacode(String areacode) {
        this.areacode = areacode;
    }

    public String getSpecialityName() {
        return specialityName;
    }

    public void setSpecialityName(String specialityName) {
        this.specialityName = specialityName;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public String getIdCardNo() {
        return idCardNo;
    }

    public void setIdCardNo(String idCardNo) {
        this.idCardNo = idCardNo;
    }

    public Date getBirthdate() {
        return birthdate;
    }

    public void setBirthdate(Date birthdate) {
        this.birthdate = birthdate;
    }

    public String getGraduateSchool() {
        return graduateSchool;
    }

    public void setGraduateSchool(String graduateSchool) {
        this.graduateSchool = graduateSchool;
    }

    public Date getGraduateDate() {
        return graduateDate;
    }

    public void setGraduateDate(Date graduateDate) {
        this.graduateDate = graduateDate;
    }

    public String getMobilephone() {
        return mobilephone;
    }

    public void setMobilephone(String mobilephone) {
        this.mobilephone = mobilephone;
    }

    public String getTel() {
        return tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getPostalAddress() {
        return postalAddress;
    }

    public void setPostalAddress(String postalAddress) {
        this.postalAddress = postalAddress;
    }

    public String getPostalCode() {
        return postalCode;
    }

    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPresentation() {
        return presentation;
    }

    public void setPresentation(String presentation) {
        this.presentation = presentation;
    }

    public Date getAddtime() {
        return addtime;
    }

    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    public String getAdduserid() {
        return adduserid;
    }

    public void setAdduserid(String adduserid) {
        this.adduserid = adduserid;
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public String getBack1() {
        return back1;
    }

    public void setBack1(String back1) {
        this.back1 = back1;
    }

    public String getBack2() {
        return back2;
    }

    public void setBack2(String back2) {
        this.back2 = back2;
    }

    public String getBack3() {
        return back3;
    }

    public void setBack3(String back3) {
        this.back3 = back3;
    }

    public base_engage getBaseEngage() {
        return baseEngage;
    }

    public void setBaseEngage(base_engage baseEngage) {
        this.baseEngage = baseEngage;
    }

    public String getRecommendSeries() {
        return recommendSeries;
    }

    public void setRecommendSeries(String recommendSeries) {
        this.recommendSeries = recommendSeries;
    }

    public String getRecommendMajor() {
        return recommendMajor;
    }

    public void setRecommendMajor(String recommendMajor) {
        this.recommendMajor = recommendMajor;
    }

    public Integer getIsRandom() {
        return isRandom;
    }

    public void setIsRandom(Integer isRandom) {
        this.isRandom = isRandom;
    }

    public base_speciality(Integer id, String personalNumber, String administrativeDutyLevel, String professialDutyLevel, String professialLevel, String professial, String jobYear, String performance, String education, String degree, String nowunit, String areacode, String specialityName, String sex, String idCardNo, Date birthdate, String graduateSchool, Date graduateDate, String mobilephone, String tel, String postalAddress, String postalCode, String email, String presentation, Date addtime, String adduserid, Integer state, String back1, String back2, String back3, base_engage baseEngage, String recommendSeries, String recommendMajor, Integer isRandom) {

        this.id = id;
        this.personalNumber = personalNumber;
        this.administrativeDutyLevel = administrativeDutyLevel;
        this.professialDutyLevel = professialDutyLevel;
        this.professialLevel = professialLevel;
        this.professial = professial;
        this.jobYear = jobYear;
        this.performance = performance;
        this.education = education;
        this.degree = degree;
        this.nowunit = nowunit;
        this.areacode = areacode;
        this.specialityName = specialityName;
        this.sex = sex;
        this.idCardNo = idCardNo;
        this.birthdate = birthdate;
        this.graduateSchool = graduateSchool;
        this.graduateDate = graduateDate;
        this.mobilephone = mobilephone;
        this.tel = tel;
        this.postalAddress = postalAddress;
        this.postalCode = postalCode;
        this.email = email;
        this.presentation = presentation;
        this.addtime = addtime;
        this.adduserid = adduserid;
        this.state = state;
        this.back1 = back1;
        this.back2 = back2;
        this.back3 = back3;
        this.baseEngage = baseEngage;
        this.recommendSeries = recommendSeries;
        this.recommendMajor = recommendMajor;
        this.isRandom = isRandom;
    }

    public base_speciality() {

    }
}