package com.hz.demo.model;

import com.hz.demo.model.shenbao.ProposerMsg;

public class proposer_group {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_PROPOSER_GROUP.ID
     *
     * @mbg.generated Sat Sep 29 16:55:15 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_PROPOSER_GROUP.GROUP_ID
     *
     * @mbg.generated Sat Sep 29 16:55:15 CST 2018
     */
    private String groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_PROPOSER_GROUP.PROPOSER_ID
     *
     * @mbg.generated Sat Sep 29 16:55:15 CST 2018
     */
    private String proposerId;

    private subject_group subjectGroup;

    private ProposerMsg proposerMsg;

    private base_proposer baseProposer;



    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_PROPOSER_GROUP.BACK1
     *
     * @mbg.generated Sat Sep 29 16:55:15 CST 2018
     */
    private String back1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_PROPOSER_GROUP.BACK2
     *
     * @mbg.generated Sat Sep 29 16:55:15 CST 2018
     */
    private String back2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_PROPOSER_GROUP.BACK3
     *
     * @mbg.generated Sat Sep 29 16:55:15 CST 2018
     */
    private String back3;

    @Override
    public String toString() {
        return "proposer_group{" +
                "id=" + id +
                ", groupId='" + groupId + '\'' +
                ", proposerId='" + proposerId + '\'' +
                ", subjectGroup=" + subjectGroup +
                ", proposerMsg=" + proposerMsg +
                ", baseProposer=" + baseProposer +
                ", back1='" + back1 + '\'' +
                ", back2='" + back2 + '\'' +
                ", back3='" + back3 + '\'' +
                '}';
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getGroupId() {
        return groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    public String getProposerId() {
        return proposerId;
    }

    public void setProposerId(String proposerId) {
        this.proposerId = proposerId;
    }

    public subject_group getSubjectGroup() {
        return subjectGroup;
    }

    public void setSubjectGroup(subject_group subjectGroup) {
        this.subjectGroup = subjectGroup;
    }

    public ProposerMsg getProposerMsg() {
        return proposerMsg;
    }

    public void setProposerMsg(ProposerMsg proposerMsg) {
        this.proposerMsg = proposerMsg;
    }

    public base_proposer getBaseProposer() {
        return baseProposer;
    }

    public void setBaseProposer(base_proposer baseProposer) {
        this.baseProposer = baseProposer;
    }

    public String getBack1() {
        return back1;
    }

    public void setBack1(String back1) {
        this.back1 = back1;
    }

    public String getBack2() {
        return back2;
    }

    public void setBack2(String back2) {
        this.back2 = back2;
    }

    public String getBack3() {
        return back3;
    }

    public void setBack3(String back3) {
        this.back3 = back3;
    }

    public proposer_group(Integer id, String groupId, String proposerId, subject_group subjectGroup, ProposerMsg proposerMsg, base_proposer baseProposer, String back1, String back2, String back3) {

        this.id = id;
        this.groupId = groupId;
        this.proposerId = proposerId;
        this.subjectGroup = subjectGroup;
        this.proposerMsg = proposerMsg;
        this.baseProposer = baseProposer;
        this.back1 = back1;
        this.back2 = back2;
        this.back3 = back3;
    }

    public proposer_group() {

    }
}