package com.hz.demo.model;

import java.math.BigDecimal;
import java.util.Date;

public class rec_reviewresultpublicity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULTPUBLICITY.ID
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULTPUBLICITY.YEAR_NO
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    private String yearNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULTPUBLICITY.AREA_CODE
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    private String areaCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULTPUBLICITY.JUDGING_CODE
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    private String judgingCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULTPUBLICITY.GROUP_ID
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    private String groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULTPUBLICITY.UNIT_CODE
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    private String unitCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULTPUBLICITY.REVIEW_SERIES
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    private String reviewSeries;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULTPUBLICITY.TITLE_LEVEL
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    private String titleLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULTPUBLICITY.POSITIONAL_TITLES
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    private String positionalTitles;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULTPUBLICITY.PROFESSIAL_CODE
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    private String professialCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULTPUBLICITY.GROUP_RESULT_YES
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    private BigDecimal groupResultYes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULTPUBLICITY.GROUP_RESULT_NO
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    private BigDecimal groupResultNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULTPUBLICITY.GROUP_RESULT_WAIVE
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    private BigDecimal groupResultWaive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULTPUBLICITY.GROUP_RESULT_OPINION
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    private String groupResultOpinion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULTPUBLICITY.GROUP_RESULT
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    private BigDecimal groupResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULTPUBLICITY.REVIEW_RESULT_YES
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    private BigDecimal reviewResultYes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULTPUBLICITY.REVIEW_RESULT_NO
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    private BigDecimal reviewResultNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULTPUBLICITY.REVIEW_RESULT_WAIVE
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    private BigDecimal reviewResultWaive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULTPUBLICITY.REVIEW_RESULT_OPINION
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    private String reviewResultOpinion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULTPUBLICITY.REVIEW_RESULT
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    private BigDecimal reviewResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULTPUBLICITY.REVIEW_TYPE
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    private String reviewType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULTPUBLICITY.USER_ID
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULTPUBLICITY.USER_NAME
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULTPUBLICITY.ID_CARD_NO
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    private String idCardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULTPUBLICITY.SEX
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULTPUBLICITY.OPT_TIME
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    private Date optTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULTPUBLICITY.OPT_USERID
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    private String optUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULTPUBLICITY.ISPUBLICITY
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    private BigDecimal ispublicity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULTPUBLICITY.BACK1
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    private String back1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULTPUBLICITY.BACK2
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    private String back2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULTPUBLICITY.BACK3
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    private String back3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_REVIEWRESULTPUBLICITY.ID
     *
     * @return the value of REC_REVIEWRESULTPUBLICITY.ID
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_REVIEWRESULTPUBLICITY.ID
     *
     * @param id the value for REC_REVIEWRESULTPUBLICITY.ID
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_REVIEWRESULTPUBLICITY.YEAR_NO
     *
     * @return the value of REC_REVIEWRESULTPUBLICITY.YEAR_NO
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public String getYearNo() {
        return yearNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_REVIEWRESULTPUBLICITY.YEAR_NO
     *
     * @param yearNo the value for REC_REVIEWRESULTPUBLICITY.YEAR_NO
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public void setYearNo(String yearNo) {
        this.yearNo = yearNo == null ? null : yearNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_REVIEWRESULTPUBLICITY.AREA_CODE
     *
     * @return the value of REC_REVIEWRESULTPUBLICITY.AREA_CODE
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_REVIEWRESULTPUBLICITY.AREA_CODE
     *
     * @param areaCode the value for REC_REVIEWRESULTPUBLICITY.AREA_CODE
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_REVIEWRESULTPUBLICITY.JUDGING_CODE
     *
     * @return the value of REC_REVIEWRESULTPUBLICITY.JUDGING_CODE
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public String getJudgingCode() {
        return judgingCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_REVIEWRESULTPUBLICITY.JUDGING_CODE
     *
     * @param judgingCode the value for REC_REVIEWRESULTPUBLICITY.JUDGING_CODE
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public void setJudgingCode(String judgingCode) {
        this.judgingCode = judgingCode == null ? null : judgingCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_REVIEWRESULTPUBLICITY.GROUP_ID
     *
     * @return the value of REC_REVIEWRESULTPUBLICITY.GROUP_ID
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_REVIEWRESULTPUBLICITY.GROUP_ID
     *
     * @param groupId the value for REC_REVIEWRESULTPUBLICITY.GROUP_ID
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_REVIEWRESULTPUBLICITY.UNIT_CODE
     *
     * @return the value of REC_REVIEWRESULTPUBLICITY.UNIT_CODE
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public String getUnitCode() {
        return unitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_REVIEWRESULTPUBLICITY.UNIT_CODE
     *
     * @param unitCode the value for REC_REVIEWRESULTPUBLICITY.UNIT_CODE
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public void setUnitCode(String unitCode) {
        this.unitCode = unitCode == null ? null : unitCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_REVIEWRESULTPUBLICITY.REVIEW_SERIES
     *
     * @return the value of REC_REVIEWRESULTPUBLICITY.REVIEW_SERIES
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public String getReviewSeries() {
        return reviewSeries;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_REVIEWRESULTPUBLICITY.REVIEW_SERIES
     *
     * @param reviewSeries the value for REC_REVIEWRESULTPUBLICITY.REVIEW_SERIES
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public void setReviewSeries(String reviewSeries) {
        this.reviewSeries = reviewSeries == null ? null : reviewSeries.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_REVIEWRESULTPUBLICITY.TITLE_LEVEL
     *
     * @return the value of REC_REVIEWRESULTPUBLICITY.TITLE_LEVEL
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public String getTitleLevel() {
        return titleLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_REVIEWRESULTPUBLICITY.TITLE_LEVEL
     *
     * @param titleLevel the value for REC_REVIEWRESULTPUBLICITY.TITLE_LEVEL
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public void setTitleLevel(String titleLevel) {
        this.titleLevel = titleLevel == null ? null : titleLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_REVIEWRESULTPUBLICITY.POSITIONAL_TITLES
     *
     * @return the value of REC_REVIEWRESULTPUBLICITY.POSITIONAL_TITLES
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public String getPositionalTitles() {
        return positionalTitles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_REVIEWRESULTPUBLICITY.POSITIONAL_TITLES
     *
     * @param positionalTitles the value for REC_REVIEWRESULTPUBLICITY.POSITIONAL_TITLES
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public void setPositionalTitles(String positionalTitles) {
        this.positionalTitles = positionalTitles == null ? null : positionalTitles.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_REVIEWRESULTPUBLICITY.PROFESSIAL_CODE
     *
     * @return the value of REC_REVIEWRESULTPUBLICITY.PROFESSIAL_CODE
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public String getProfessialCode() {
        return professialCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_REVIEWRESULTPUBLICITY.PROFESSIAL_CODE
     *
     * @param professialCode the value for REC_REVIEWRESULTPUBLICITY.PROFESSIAL_CODE
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public void setProfessialCode(String professialCode) {
        this.professialCode = professialCode == null ? null : professialCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_REVIEWRESULTPUBLICITY.GROUP_RESULT_YES
     *
     * @return the value of REC_REVIEWRESULTPUBLICITY.GROUP_RESULT_YES
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public BigDecimal getGroupResultYes() {
        return groupResultYes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_REVIEWRESULTPUBLICITY.GROUP_RESULT_YES
     *
     * @param groupResultYes the value for REC_REVIEWRESULTPUBLICITY.GROUP_RESULT_YES
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public void setGroupResultYes(BigDecimal groupResultYes) {
        this.groupResultYes = groupResultYes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_REVIEWRESULTPUBLICITY.GROUP_RESULT_NO
     *
     * @return the value of REC_REVIEWRESULTPUBLICITY.GROUP_RESULT_NO
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public BigDecimal getGroupResultNo() {
        return groupResultNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_REVIEWRESULTPUBLICITY.GROUP_RESULT_NO
     *
     * @param groupResultNo the value for REC_REVIEWRESULTPUBLICITY.GROUP_RESULT_NO
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public void setGroupResultNo(BigDecimal groupResultNo) {
        this.groupResultNo = groupResultNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_REVIEWRESULTPUBLICITY.GROUP_RESULT_WAIVE
     *
     * @return the value of REC_REVIEWRESULTPUBLICITY.GROUP_RESULT_WAIVE
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public BigDecimal getGroupResultWaive() {
        return groupResultWaive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_REVIEWRESULTPUBLICITY.GROUP_RESULT_WAIVE
     *
     * @param groupResultWaive the value for REC_REVIEWRESULTPUBLICITY.GROUP_RESULT_WAIVE
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public void setGroupResultWaive(BigDecimal groupResultWaive) {
        this.groupResultWaive = groupResultWaive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_REVIEWRESULTPUBLICITY.GROUP_RESULT_OPINION
     *
     * @return the value of REC_REVIEWRESULTPUBLICITY.GROUP_RESULT_OPINION
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public String getGroupResultOpinion() {
        return groupResultOpinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_REVIEWRESULTPUBLICITY.GROUP_RESULT_OPINION
     *
     * @param groupResultOpinion the value for REC_REVIEWRESULTPUBLICITY.GROUP_RESULT_OPINION
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public void setGroupResultOpinion(String groupResultOpinion) {
        this.groupResultOpinion = groupResultOpinion == null ? null : groupResultOpinion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_REVIEWRESULTPUBLICITY.GROUP_RESULT
     *
     * @return the value of REC_REVIEWRESULTPUBLICITY.GROUP_RESULT
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public BigDecimal getGroupResult() {
        return groupResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_REVIEWRESULTPUBLICITY.GROUP_RESULT
     *
     * @param groupResult the value for REC_REVIEWRESULTPUBLICITY.GROUP_RESULT
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public void setGroupResult(BigDecimal groupResult) {
        this.groupResult = groupResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_REVIEWRESULTPUBLICITY.REVIEW_RESULT_YES
     *
     * @return the value of REC_REVIEWRESULTPUBLICITY.REVIEW_RESULT_YES
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public BigDecimal getReviewResultYes() {
        return reviewResultYes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_REVIEWRESULTPUBLICITY.REVIEW_RESULT_YES
     *
     * @param reviewResultYes the value for REC_REVIEWRESULTPUBLICITY.REVIEW_RESULT_YES
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public void setReviewResultYes(BigDecimal reviewResultYes) {
        this.reviewResultYes = reviewResultYes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_REVIEWRESULTPUBLICITY.REVIEW_RESULT_NO
     *
     * @return the value of REC_REVIEWRESULTPUBLICITY.REVIEW_RESULT_NO
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public BigDecimal getReviewResultNo() {
        return reviewResultNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_REVIEWRESULTPUBLICITY.REVIEW_RESULT_NO
     *
     * @param reviewResultNo the value for REC_REVIEWRESULTPUBLICITY.REVIEW_RESULT_NO
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public void setReviewResultNo(BigDecimal reviewResultNo) {
        this.reviewResultNo = reviewResultNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_REVIEWRESULTPUBLICITY.REVIEW_RESULT_WAIVE
     *
     * @return the value of REC_REVIEWRESULTPUBLICITY.REVIEW_RESULT_WAIVE
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public BigDecimal getReviewResultWaive() {
        return reviewResultWaive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_REVIEWRESULTPUBLICITY.REVIEW_RESULT_WAIVE
     *
     * @param reviewResultWaive the value for REC_REVIEWRESULTPUBLICITY.REVIEW_RESULT_WAIVE
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public void setReviewResultWaive(BigDecimal reviewResultWaive) {
        this.reviewResultWaive = reviewResultWaive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_REVIEWRESULTPUBLICITY.REVIEW_RESULT_OPINION
     *
     * @return the value of REC_REVIEWRESULTPUBLICITY.REVIEW_RESULT_OPINION
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public String getReviewResultOpinion() {
        return reviewResultOpinion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_REVIEWRESULTPUBLICITY.REVIEW_RESULT_OPINION
     *
     * @param reviewResultOpinion the value for REC_REVIEWRESULTPUBLICITY.REVIEW_RESULT_OPINION
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public void setReviewResultOpinion(String reviewResultOpinion) {
        this.reviewResultOpinion = reviewResultOpinion == null ? null : reviewResultOpinion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_REVIEWRESULTPUBLICITY.REVIEW_RESULT
     *
     * @return the value of REC_REVIEWRESULTPUBLICITY.REVIEW_RESULT
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public BigDecimal getReviewResult() {
        return reviewResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_REVIEWRESULTPUBLICITY.REVIEW_RESULT
     *
     * @param reviewResult the value for REC_REVIEWRESULTPUBLICITY.REVIEW_RESULT
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public void setReviewResult(BigDecimal reviewResult) {
        this.reviewResult = reviewResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_REVIEWRESULTPUBLICITY.REVIEW_TYPE
     *
     * @return the value of REC_REVIEWRESULTPUBLICITY.REVIEW_TYPE
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public String getReviewType() {
        return reviewType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_REVIEWRESULTPUBLICITY.REVIEW_TYPE
     *
     * @param reviewType the value for REC_REVIEWRESULTPUBLICITY.REVIEW_TYPE
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public void setReviewType(String reviewType) {
        this.reviewType = reviewType == null ? null : reviewType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_REVIEWRESULTPUBLICITY.USER_ID
     *
     * @return the value of REC_REVIEWRESULTPUBLICITY.USER_ID
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_REVIEWRESULTPUBLICITY.USER_ID
     *
     * @param userId the value for REC_REVIEWRESULTPUBLICITY.USER_ID
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_REVIEWRESULTPUBLICITY.USER_NAME
     *
     * @return the value of REC_REVIEWRESULTPUBLICITY.USER_NAME
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_REVIEWRESULTPUBLICITY.USER_NAME
     *
     * @param userName the value for REC_REVIEWRESULTPUBLICITY.USER_NAME
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_REVIEWRESULTPUBLICITY.ID_CARD_NO
     *
     * @return the value of REC_REVIEWRESULTPUBLICITY.ID_CARD_NO
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public String getIdCardNo() {
        return idCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_REVIEWRESULTPUBLICITY.ID_CARD_NO
     *
     * @param idCardNo the value for REC_REVIEWRESULTPUBLICITY.ID_CARD_NO
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public void setIdCardNo(String idCardNo) {
        this.idCardNo = idCardNo == null ? null : idCardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_REVIEWRESULTPUBLICITY.SEX
     *
     * @return the value of REC_REVIEWRESULTPUBLICITY.SEX
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_REVIEWRESULTPUBLICITY.SEX
     *
     * @param sex the value for REC_REVIEWRESULTPUBLICITY.SEX
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_REVIEWRESULTPUBLICITY.OPT_TIME
     *
     * @return the value of REC_REVIEWRESULTPUBLICITY.OPT_TIME
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public Date getOptTime() {
        return optTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_REVIEWRESULTPUBLICITY.OPT_TIME
     *
     * @param optTime the value for REC_REVIEWRESULTPUBLICITY.OPT_TIME
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public void setOptTime(Date optTime) {
        this.optTime = optTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_REVIEWRESULTPUBLICITY.OPT_USERID
     *
     * @return the value of REC_REVIEWRESULTPUBLICITY.OPT_USERID
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public String getOptUserid() {
        return optUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_REVIEWRESULTPUBLICITY.OPT_USERID
     *
     * @param optUserid the value for REC_REVIEWRESULTPUBLICITY.OPT_USERID
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public void setOptUserid(String optUserid) {
        this.optUserid = optUserid == null ? null : optUserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_REVIEWRESULTPUBLICITY.ISPUBLICITY
     *
     * @return the value of REC_REVIEWRESULTPUBLICITY.ISPUBLICITY
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public BigDecimal getIspublicity() {
        return ispublicity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_REVIEWRESULTPUBLICITY.ISPUBLICITY
     *
     * @param ispublicity the value for REC_REVIEWRESULTPUBLICITY.ISPUBLICITY
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public void setIspublicity(BigDecimal ispublicity) {
        this.ispublicity = ispublicity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_REVIEWRESULTPUBLICITY.BACK1
     *
     * @return the value of REC_REVIEWRESULTPUBLICITY.BACK1
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public String getBack1() {
        return back1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_REVIEWRESULTPUBLICITY.BACK1
     *
     * @param back1 the value for REC_REVIEWRESULTPUBLICITY.BACK1
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public void setBack1(String back1) {
        this.back1 = back1 == null ? null : back1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_REVIEWRESULTPUBLICITY.BACK2
     *
     * @return the value of REC_REVIEWRESULTPUBLICITY.BACK2
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public String getBack2() {
        return back2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_REVIEWRESULTPUBLICITY.BACK2
     *
     * @param back2 the value for REC_REVIEWRESULTPUBLICITY.BACK2
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public void setBack2(String back2) {
        this.back2 = back2 == null ? null : back2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_REVIEWRESULTPUBLICITY.BACK3
     *
     * @return the value of REC_REVIEWRESULTPUBLICITY.BACK3
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public String getBack3() {
        return back3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_REVIEWRESULTPUBLICITY.BACK3
     *
     * @param back3 the value for REC_REVIEWRESULTPUBLICITY.BACK3
     *
     * @mbg.generated Fri Nov 02 09:34:08 CST 2018
     */
    public void setBack3(String back3) {
        this.back3 = back3 == null ? null : back3.trim();
    }
}