package com.hz.demo.model;

import java.math.BigDecimal;
import java.util.Date;

public class rec_reviewresult {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULT.ID
     *
     * @mbg.generated Wed Oct 31 14:48:07 CST 2018
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULT.YEAR_NO
     *
     * @mbg.generated Wed Oct 31 14:48:07 CST 2018
     */
    private String yearNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULT.AREA_CODE
     *
     * @mbg.generated Wed Oct 31 14:48:07 CST 2018
     */
    private String areaCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULT.JUDGING_CODE
     *
     * @mbg.generated Wed Oct 31 14:48:07 CST 2018
     */
    private String judgingCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULT.GROUP_ID
     *
     * @mbg.generated Wed Oct 31 14:48:07 CST 2018
     */
    private String groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULT.UNIT_CODE
     *
     * @mbg.generated Wed Oct 31 14:48:07 CST 2018
     */
    private String unitCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULT.REVIEW_SERIES
     *
     * @mbg.generated Wed Oct 31 14:48:07 CST 2018
     */
    private String reviewSeries;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULT.TITLE_LEVEL
     *
     * @mbg.generated Wed Oct 31 14:48:07 CST 2018
     */
    private String titleLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULT.POSITIONAL_TITLES
     *
     * @mbg.generated Wed Oct 31 14:48:07 CST 2018
     */
    private String positionalTitles;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULT.PROFESSIAL_CODE
     *
     * @mbg.generated Wed Oct 31 14:48:07 CST 2018
     */
    private String professialCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULT.GROUP_RESULT_YES
     *
     * @mbg.generated Wed Oct 31 14:48:07 CST 2018
     */
    private BigDecimal groupResultYes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULT.GROUP_RESULT_NO
     *
     * @mbg.generated Wed Oct 31 14:48:07 CST 2018
     */
    private BigDecimal groupResultNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULT.GROUP_RESULT_WAIVE
     *
     * @mbg.generated Wed Oct 31 14:48:07 CST 2018
     */
    private BigDecimal groupResultWaive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULT.GROUP_RESULT_OPINION
     *
     * @mbg.generated Wed Oct 31 14:48:07 CST 2018
     */
    private String groupResultOpinion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULT.GROUP_RESULT
     *
     * @mbg.generated Wed Oct 31 14:48:07 CST 2018
     */
    private BigDecimal groupResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULT.REVIEW_RESULT_YES
     *
     * @mbg.generated Wed Oct 31 14:48:07 CST 2018
     */
    private BigDecimal reviewResultYes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULT.REVIEW_RESULT_NO
     *
     * @mbg.generated Wed Oct 31 14:48:07 CST 2018
     */
    private BigDecimal reviewResultNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULT.REVIEW_RESULT_WAIVE
     *
     * @mbg.generated Wed Oct 31 14:48:07 CST 2018
     */
    private BigDecimal reviewResultWaive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULT.REVIEW_RESULT_OPINION
     *
     * @mbg.generated Wed Oct 31 14:48:07 CST 2018
     */
    private String reviewResultOpinion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULT.REVIEW_RESULT
     *
     * @mbg.generated Wed Oct 31 14:48:07 CST 2018
     */
    private BigDecimal reviewResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULT.REVIEW_TYPE
     *
     * @mbg.generated Wed Oct 31 14:48:07 CST 2018
     */
    private String reviewType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULT.USER_ID
     *
     * @mbg.generated Wed Oct 31 14:48:07 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULT.USER_NAME
     *
     * @mbg.generated Wed Oct 31 14:48:07 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULT.ID_CARD_NO
     *
     * @mbg.generated Wed Oct 31 14:48:07 CST 2018
     */
    private String idCardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULT.SEX
     *
     * @mbg.generated Wed Oct 31 14:48:07 CST 2018
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULT.OPT_TIME
     *
     * @mbg.generated Wed Oct 31 14:48:07 CST 2018
     */
    private Date optTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULT.OPT_USERID
     *
     * @mbg.generated Wed Oct 31 14:48:07 CST 2018
     */
    private String optUserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULT.BACK1
     *
     * @mbg.generated Wed Oct 31 14:48:07 CST 2018
     */
    private String back1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULT.BACK2
     *
     * @mbg.generated Wed Oct 31 14:48:07 CST 2018
     */
    private String back2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_REVIEWRESULT.BACK3
     *
     * @mbg.generated Wed Oct 31 14:48:07 CST 2018
     */
    private String back3;


    private Integer resultState;

    @Override
    public String toString() {
        return "rec_reviewresult{" +
                "id=" + id +
                ", yearNo='" + yearNo + '\'' +
                ", areaCode='" + areaCode + '\'' +
                ", judgingCode='" + judgingCode + '\'' +
                ", groupId='" + groupId + '\'' +
                ", unitCode='" + unitCode + '\'' +
                ", reviewSeries='" + reviewSeries + '\'' +
                ", titleLevel='" + titleLevel + '\'' +
                ", positionalTitles='" + positionalTitles + '\'' +
                ", professialCode='" + professialCode + '\'' +
                ", groupResultYes=" + groupResultYes +
                ", groupResultNo=" + groupResultNo +
                ", groupResultWaive=" + groupResultWaive +
                ", groupResultOpinion='" + groupResultOpinion + '\'' +
                ", groupResult=" + groupResult +
                ", reviewResultYes=" + reviewResultYes +
                ", reviewResultNo=" + reviewResultNo +
                ", reviewResultWaive=" + reviewResultWaive +
                ", reviewResultOpinion='" + reviewResultOpinion + '\'' +
                ", reviewResult=" + reviewResult +
                ", reviewType='" + reviewType + '\'' +
                ", userId='" + userId + '\'' +
                ", userName='" + userName + '\'' +
                ", idCardNo='" + idCardNo + '\'' +
                ", sex='" + sex + '\'' +
                ", optTime=" + optTime +
                ", optUserid='" + optUserid + '\'' +
                ", back1='" + back1 + '\'' +
                ", back2='" + back2 + '\'' +
                ", back3='" + back3 + '\'' +
                ", resultState='" + resultState + '\'' +
                '}';
    }

    public BigDecimal getId() {
        return id;
    }

    public void setId(BigDecimal id) {
        this.id = id;
    }

    public String getYearNo() {
        return yearNo;
    }

    public void setYearNo(String yearNo) {
        this.yearNo = yearNo;
    }

    public String getAreaCode() {
        return areaCode;
    }

    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }

    public String getJudgingCode() {
        return judgingCode;
    }

    public void setJudgingCode(String judgingCode) {
        this.judgingCode = judgingCode;
    }

    public String getGroupId() {
        return groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    public String getUnitCode() {
        return unitCode;
    }

    public void setUnitCode(String unitCode) {
        this.unitCode = unitCode;
    }

    public String getReviewSeries() {
        return reviewSeries;
    }

    public void setReviewSeries(String reviewSeries) {
        this.reviewSeries = reviewSeries;
    }

    public String getTitleLevel() {
        return titleLevel;
    }

    public void setTitleLevel(String titleLevel) {
        this.titleLevel = titleLevel;
    }

    public String getPositionalTitles() {
        return positionalTitles;
    }

    public void setPositionalTitles(String positionalTitles) {
        this.positionalTitles = positionalTitles;
    }

    public String getProfessialCode() {
        return professialCode;
    }

    public void setProfessialCode(String professialCode) {
        this.professialCode = professialCode;
    }

    public BigDecimal getGroupResultYes() {
        return groupResultYes;
    }

    public void setGroupResultYes(BigDecimal groupResultYes) {
        this.groupResultYes = groupResultYes;
    }

    public BigDecimal getGroupResultNo() {
        return groupResultNo;
    }

    public void setGroupResultNo(BigDecimal groupResultNo) {
        this.groupResultNo = groupResultNo;
    }

    public BigDecimal getGroupResultWaive() {
        return groupResultWaive;
    }

    public void setGroupResultWaive(BigDecimal groupResultWaive) {
        this.groupResultWaive = groupResultWaive;
    }

    public String getGroupResultOpinion() {
        return groupResultOpinion;
    }

    public void setGroupResultOpinion(String groupResultOpinion) {
        this.groupResultOpinion = groupResultOpinion;
    }

    public BigDecimal getGroupResult() {
        return groupResult;
    }

    public void setGroupResult(BigDecimal groupResult) {
        this.groupResult = groupResult;
    }

    public BigDecimal getReviewResultYes() {
        return reviewResultYes;
    }

    public void setReviewResultYes(BigDecimal reviewResultYes) {
        this.reviewResultYes = reviewResultYes;
    }

    public BigDecimal getReviewResultNo() {
        return reviewResultNo;
    }

    public void setReviewResultNo(BigDecimal reviewResultNo) {
        this.reviewResultNo = reviewResultNo;
    }

    public BigDecimal getReviewResultWaive() {
        return reviewResultWaive;
    }

    public void setReviewResultWaive(BigDecimal reviewResultWaive) {
        this.reviewResultWaive = reviewResultWaive;
    }

    public String getReviewResultOpinion() {
        return reviewResultOpinion;
    }

    public void setReviewResultOpinion(String reviewResultOpinion) {
        this.reviewResultOpinion = reviewResultOpinion;
    }

    public BigDecimal getReviewResult() {
        return reviewResult;
    }

    public void setReviewResult(BigDecimal reviewResult) {
        this.reviewResult = reviewResult;
    }

    public String getReviewType() {
        return reviewType;
    }

    public void setReviewType(String reviewType) {
        this.reviewType = reviewType;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getIdCardNo() {
        return idCardNo;
    }

    public void setIdCardNo(String idCardNo) {
        this.idCardNo = idCardNo;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public Date getOptTime() {
        return optTime;
    }

    public void setOptTime(Date optTime) {
        this.optTime = optTime;
    }

    public String getOptUserid() {
        return optUserid;
    }

    public void setOptUserid(String optUserid) {
        this.optUserid = optUserid;
    }

    public String getBack1() {
        return back1;
    }

    public void setBack1(String back1) {
        this.back1 = back1;
    }

    public String getBack2() {
        return back2;
    }

    public void setBack2(String back2) {
        this.back2 = back2;
    }

    public String getBack3() {
        return back3;
    }

    public void setBack3(String back3) {
        this.back3 = back3;
    }

    public Integer getResultState() {
        return resultState;
    }

    public void setResultState(Integer resultState) {
        this.resultState = resultState;
    }

    public rec_reviewresult(BigDecimal id, String yearNo, String areaCode, String judgingCode, String groupId, String unitCode, String reviewSeries, String titleLevel, String positionalTitles, String professialCode, BigDecimal groupResultYes, BigDecimal groupResultNo, BigDecimal groupResultWaive, String groupResultOpinion, BigDecimal groupResult, BigDecimal reviewResultYes, BigDecimal reviewResultNo, BigDecimal reviewResultWaive, String reviewResultOpinion, BigDecimal reviewResult, String reviewType, String userId, String userName, String idCardNo, String sex, Date optTime, String optUserid, String back1, String back2, String back3, Integer resultState) {

        this.id = id;
        this.yearNo = yearNo;
        this.areaCode = areaCode;
        this.judgingCode = judgingCode;
        this.groupId = groupId;
        this.unitCode = unitCode;
        this.reviewSeries = reviewSeries;
        this.titleLevel = titleLevel;
        this.positionalTitles = positionalTitles;
        this.professialCode = professialCode;
        this.groupResultYes = groupResultYes;
        this.groupResultNo = groupResultNo;
        this.groupResultWaive = groupResultWaive;
        this.groupResultOpinion = groupResultOpinion;
        this.groupResult = groupResult;
        this.reviewResultYes = reviewResultYes;
        this.reviewResultNo = reviewResultNo;
        this.reviewResultWaive = reviewResultWaive;
        this.reviewResultOpinion = reviewResultOpinion;
        this.reviewResult = reviewResult;
        this.reviewType = reviewType;
        this.userId = userId;
        this.userName = userName;
        this.idCardNo = idCardNo;
        this.sex = sex;
        this.optTime = optTime;
        this.optUserid = optUserid;
        this.back1 = back1;
        this.back2 = back2;
        this.back3 = back3;
        this.resultState = resultState;
    }

    public rec_reviewresult() {

    }
}