package com.hz.demo.model;

import java.math.BigDecimal;
import java.util.Date;

public class rec_examresult {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_EXAMRESULT.ID
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_EXAMRESULT.YEAR_NO
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    private String yearNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_EXAMRESULT.AREA_CODE
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    private String areaCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_EXAMRESULT.USER_NAME
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_EXAMRESULT.SEX
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_EXAMRESULT.TICKET_NUMBER
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    private String ticketNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_EXAMRESULT.CERTIFICATE_NUMBER
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    private String certificateNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_EXAMRESULT.UNIT_NAME
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    private String unitName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_EXAMRESULT.TITLE_LEVEL
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    private String titleLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_EXAMRESULT.REVIEW_SERIES
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    private String reviewSeries;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_EXAMRESULT.PROFESSIAL_CODE
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    private String professialCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_EXAMRESULT.POSITIONAL_TITLES
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    private String positionalTitles;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_EXAMRESULT.ID_CARD_NO
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    private String idCardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_EXAMRESULT.GETTIME
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    private Date gettime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_EXAMRESULT.FILE_NUMBER
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    private String fileNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_EXAMRESULT.BIRTHDAY
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_EXAMRESULT.MANAGER_NO
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    private String managerNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_EXAMRESULT.EXAM_CLASS
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    private String examClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_EXAMRESULT.EXAM_NAME
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    private String examName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_EXAMRESULT.ADDTIME
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    private Date addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_EXAMRESULT.ADDUSERID
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    private String adduserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_EXAMRESULT.BACK1
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    private String back1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_EXAMRESULT.BACK2
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    private String back2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_EXAMRESULT.BACK3
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    private String back3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_EXAMRESULT.ID
     *
     * @return the value of REC_EXAMRESULT.ID
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_EXAMRESULT.ID
     *
     * @param id the value for REC_EXAMRESULT.ID
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_EXAMRESULT.YEAR_NO
     *
     * @return the value of REC_EXAMRESULT.YEAR_NO
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public String getYearNo() {
        return yearNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_EXAMRESULT.YEAR_NO
     *
     * @param yearNo the value for REC_EXAMRESULT.YEAR_NO
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public void setYearNo(String yearNo) {
        this.yearNo = yearNo == null ? null : yearNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_EXAMRESULT.AREA_CODE
     *
     * @return the value of REC_EXAMRESULT.AREA_CODE
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_EXAMRESULT.AREA_CODE
     *
     * @param areaCode the value for REC_EXAMRESULT.AREA_CODE
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_EXAMRESULT.USER_NAME
     *
     * @return the value of REC_EXAMRESULT.USER_NAME
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_EXAMRESULT.USER_NAME
     *
     * @param userName the value for REC_EXAMRESULT.USER_NAME
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_EXAMRESULT.SEX
     *
     * @return the value of REC_EXAMRESULT.SEX
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_EXAMRESULT.SEX
     *
     * @param sex the value for REC_EXAMRESULT.SEX
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_EXAMRESULT.TICKET_NUMBER
     *
     * @return the value of REC_EXAMRESULT.TICKET_NUMBER
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public String getTicketNumber() {
        return ticketNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_EXAMRESULT.TICKET_NUMBER
     *
     * @param ticketNumber the value for REC_EXAMRESULT.TICKET_NUMBER
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public void setTicketNumber(String ticketNumber) {
        this.ticketNumber = ticketNumber == null ? null : ticketNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_EXAMRESULT.CERTIFICATE_NUMBER
     *
     * @return the value of REC_EXAMRESULT.CERTIFICATE_NUMBER
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public String getCertificateNumber() {
        return certificateNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_EXAMRESULT.CERTIFICATE_NUMBER
     *
     * @param certificateNumber the value for REC_EXAMRESULT.CERTIFICATE_NUMBER
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public void setCertificateNumber(String certificateNumber) {
        this.certificateNumber = certificateNumber == null ? null : certificateNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_EXAMRESULT.UNIT_NAME
     *
     * @return the value of REC_EXAMRESULT.UNIT_NAME
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public String getUnitName() {
        return unitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_EXAMRESULT.UNIT_NAME
     *
     * @param unitName the value for REC_EXAMRESULT.UNIT_NAME
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public void setUnitName(String unitName) {
        this.unitName = unitName == null ? null : unitName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_EXAMRESULT.TITLE_LEVEL
     *
     * @return the value of REC_EXAMRESULT.TITLE_LEVEL
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public String getTitleLevel() {
        return titleLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_EXAMRESULT.TITLE_LEVEL
     *
     * @param titleLevel the value for REC_EXAMRESULT.TITLE_LEVEL
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public void setTitleLevel(String titleLevel) {
        this.titleLevel = titleLevel == null ? null : titleLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_EXAMRESULT.REVIEW_SERIES
     *
     * @return the value of REC_EXAMRESULT.REVIEW_SERIES
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public String getReviewSeries() {
        return reviewSeries;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_EXAMRESULT.REVIEW_SERIES
     *
     * @param reviewSeries the value for REC_EXAMRESULT.REVIEW_SERIES
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public void setReviewSeries(String reviewSeries) {
        this.reviewSeries = reviewSeries == null ? null : reviewSeries.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_EXAMRESULT.PROFESSIAL_CODE
     *
     * @return the value of REC_EXAMRESULT.PROFESSIAL_CODE
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public String getProfessialCode() {
        return professialCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_EXAMRESULT.PROFESSIAL_CODE
     *
     * @param professialCode the value for REC_EXAMRESULT.PROFESSIAL_CODE
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public void setProfessialCode(String professialCode) {
        this.professialCode = professialCode == null ? null : professialCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_EXAMRESULT.POSITIONAL_TITLES
     *
     * @return the value of REC_EXAMRESULT.POSITIONAL_TITLES
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public String getPositionalTitles() {
        return positionalTitles;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_EXAMRESULT.POSITIONAL_TITLES
     *
     * @param positionalTitles the value for REC_EXAMRESULT.POSITIONAL_TITLES
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public void setPositionalTitles(String positionalTitles) {
        this.positionalTitles = positionalTitles == null ? null : positionalTitles.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_EXAMRESULT.ID_CARD_NO
     *
     * @return the value of REC_EXAMRESULT.ID_CARD_NO
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public String getIdCardNo() {
        return idCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_EXAMRESULT.ID_CARD_NO
     *
     * @param idCardNo the value for REC_EXAMRESULT.ID_CARD_NO
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public void setIdCardNo(String idCardNo) {
        this.idCardNo = idCardNo == null ? null : idCardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_EXAMRESULT.GETTIME
     *
     * @return the value of REC_EXAMRESULT.GETTIME
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public Date getGettime() {
        return gettime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_EXAMRESULT.GETTIME
     *
     * @param gettime the value for REC_EXAMRESULT.GETTIME
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public void setGettime(Date gettime) {
        this.gettime = gettime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_EXAMRESULT.FILE_NUMBER
     *
     * @return the value of REC_EXAMRESULT.FILE_NUMBER
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public String getFileNumber() {
        return fileNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_EXAMRESULT.FILE_NUMBER
     *
     * @param fileNumber the value for REC_EXAMRESULT.FILE_NUMBER
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public void setFileNumber(String fileNumber) {
        this.fileNumber = fileNumber == null ? null : fileNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_EXAMRESULT.BIRTHDAY
     *
     * @return the value of REC_EXAMRESULT.BIRTHDAY
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_EXAMRESULT.BIRTHDAY
     *
     * @param birthday the value for REC_EXAMRESULT.BIRTHDAY
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_EXAMRESULT.MANAGER_NO
     *
     * @return the value of REC_EXAMRESULT.MANAGER_NO
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public String getManagerNo() {
        return managerNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_EXAMRESULT.MANAGER_NO
     *
     * @param managerNo the value for REC_EXAMRESULT.MANAGER_NO
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public void setManagerNo(String managerNo) {
        this.managerNo = managerNo == null ? null : managerNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_EXAMRESULT.EXAM_CLASS
     *
     * @return the value of REC_EXAMRESULT.EXAM_CLASS
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public String getExamClass() {
        return examClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_EXAMRESULT.EXAM_CLASS
     *
     * @param examClass the value for REC_EXAMRESULT.EXAM_CLASS
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public void setExamClass(String examClass) {
        this.examClass = examClass == null ? null : examClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_EXAMRESULT.EXAM_NAME
     *
     * @return the value of REC_EXAMRESULT.EXAM_NAME
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public String getExamName() {
        return examName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_EXAMRESULT.EXAM_NAME
     *
     * @param examName the value for REC_EXAMRESULT.EXAM_NAME
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public void setExamName(String examName) {
        this.examName = examName == null ? null : examName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_EXAMRESULT.ADDTIME
     *
     * @return the value of REC_EXAMRESULT.ADDTIME
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_EXAMRESULT.ADDTIME
     *
     * @param addtime the value for REC_EXAMRESULT.ADDTIME
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_EXAMRESULT.ADDUSERID
     *
     * @return the value of REC_EXAMRESULT.ADDUSERID
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public String getAdduserid() {
        return adduserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_EXAMRESULT.ADDUSERID
     *
     * @param adduserid the value for REC_EXAMRESULT.ADDUSERID
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public void setAdduserid(String adduserid) {
        this.adduserid = adduserid == null ? null : adduserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_EXAMRESULT.BACK1
     *
     * @return the value of REC_EXAMRESULT.BACK1
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public String getBack1() {
        return back1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_EXAMRESULT.BACK1
     *
     * @param back1 the value for REC_EXAMRESULT.BACK1
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public void setBack1(String back1) {
        this.back1 = back1 == null ? null : back1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_EXAMRESULT.BACK2
     *
     * @return the value of REC_EXAMRESULT.BACK2
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public String getBack2() {
        return back2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_EXAMRESULT.BACK2
     *
     * @param back2 the value for REC_EXAMRESULT.BACK2
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public void setBack2(String back2) {
        this.back2 = back2 == null ? null : back2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_EXAMRESULT.BACK3
     *
     * @return the value of REC_EXAMRESULT.BACK3
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public String getBack3() {
        return back3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REC_EXAMRESULT.BACK3
     *
     * @param back3 the value for REC_EXAMRESULT.BACK3
     *
     * @mbg.generated Thu Nov 15 11:30:14 CST 2018
     */
    public void setBack3(String back3) {
        this.back3 = back3 == null ? null : back3.trim();
    }
}