package com.hz.demo.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class rec_fileManager {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_FILEMANAGER.ID
     *
     * @mbg.generated Tue Nov 06 17:25:37 CST 2018
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_FILEMANAGER.FILE_CODE
     *
     * @mbg.generated Tue Nov 06 17:25:37 CST 2018
     */
    private String fileCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_FILEMANAGER.YEAR_NO
     *
     * @mbg.generated Tue Nov 06 17:25:37 CST 2018
     */
    private String yearNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_FILEMANAGER.FILE_TITLE
     *
     * @mbg.generated Tue Nov 06 17:25:37 CST 2018
     */
    private String fileTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_FILEMANAGER.FILE_PATH
     *
     * @mbg.generated Tue Nov 06 17:25:37 CST 2018
     */
    private String filePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_FILEMANAGER.ADDTIME
     *
     * @mbg.generated Tue Nov 06 17:25:37 CST 2018
     */
    private Date addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_FILEMANAGER.BACK1
     *
     * @mbg.generated Tue Nov 06 17:25:37 CST 2018
     */
    private String back1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_FILEMANAGER.BACK2
     *
     * @mbg.generated Tue Nov 06 17:25:37 CST 2018
     */
    private String back2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REC_FILEMANAGER.BACK3
     *
     * @mbg.generated Tue Nov 06 17:25:37 CST 2018
     */
    private String back3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REC_FILEMANAGER.ID
     *
     * @return the value of REC_FILEMANAGER.ID
     *
     * @mbg.generated Tue Nov 06 17:25:37 CST 2018
     */
    private List<rec_result> recResultList;

    @Override
    public String toString() {
        return "rec_fileManager{" +
                "id=" + id +
                ", fileCode='" + fileCode + '\'' +
                ", yearNo='" + yearNo + '\'' +
                ", fileTitle='" + fileTitle + '\'' +
                ", filePath='" + filePath + '\'' +
                ", addtime=" + addtime +
                ", back1='" + back1 + '\'' +
                ", back2='" + back2 + '\'' +
                ", back3='" + back3 + '\'' +
                ", recResultList=" + recResultList +
                '}';
    }

    public BigDecimal getId() {
        return id;
    }

    public void setId(BigDecimal id) {
        this.id = id;
    }

    public String getFileCode() {
        return fileCode;
    }

    public void setFileCode(String fileCode) {
        this.fileCode = fileCode;
    }

    public String getYearNo() {
        return yearNo;
    }

    public void setYearNo(String yearNo) {
        this.yearNo = yearNo;
    }

    public String getFileTitle() {
        return fileTitle;
    }

    public void setFileTitle(String fileTitle) {
        this.fileTitle = fileTitle;
    }

    public String getFilePath() {
        return filePath;
    }

    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    public Date getAddtime() {
        return addtime;
    }

    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    public String getBack1() {
        return back1;
    }

    public void setBack1(String back1) {
        this.back1 = back1;
    }

    public String getBack2() {
        return back2;
    }

    public void setBack2(String back2) {
        this.back2 = back2;
    }

    public String getBack3() {
        return back3;
    }

    public void setBack3(String back3) {
        this.back3 = back3;
    }

    public List<rec_result> getRecResultList() {
        return recResultList;
    }

    public void setRecResultList(List<rec_result> recResultList) {
        this.recResultList = recResultList;
    }

    public rec_fileManager(BigDecimal id, String fileCode, String yearNo, String fileTitle, String filePath, Date addtime, String back1, String back2, String back3, List<rec_result> recResultList) {

        this.id = id;
        this.fileCode = fileCode;
        this.yearNo = yearNo;
        this.fileTitle = fileTitle;
        this.filePath = filePath;
        this.addtime = addtime;
        this.back1 = back1;
        this.back2 = back2;
        this.back3 = back3;
        this.recResultList = recResultList;
    }

    public rec_fileManager() {

    }
}