package com.hz.demo.model;

import java.math.BigDecimal;

public class speciality_group {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY_GROUP.ID
     *
     * @mbg.generated Fri Sep 21 13:53:26 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY_GROUP.GROUP_ID
     *
     * @mbg.generated Fri Sep 21 13:53:26 CST 2018
     */
    private String groupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY_GROUP.SPECIALITY_ID
     *
     * @mbg.generated Fri Sep 21 13:53:26 CST 2018
     */
    private String specialityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY_GROUP.BACK1
     *
     * @mbg.generated Fri Sep 21 13:53:26 CST 2018
     */

    private subject_group subjectGroup;

    private base_speciality baseSpeciality;

    private String back1;
    private String judgingCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY_GROUP.BACK2
     *
     * @mbg.generated Fri Sep 21 13:53:26 CST 2018
     */
    private String back2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SPECIALITY_GROUP.BACK3
     *
     * @mbg.generated Fri Sep 21 13:53:26 CST 2018
     */
    private String back3;

    @Override
    public String toString() {
        return "speciality_group{" +
                "id=" + id +
                ", groupId='" + groupId + '\'' +
                ", specialityId='" + specialityId + '\'' +
                ", subjectGroup=" + subjectGroup +
                ", baseSpeciality=" + baseSpeciality +
                ", back1='" + back1 + '\'' +
                ", back2='" + back2 + '\'' +
                ", back3='" + back3 + '\'' +
                '}';
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getGroupId() {
        return groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    public String getSpecialityId() {
        return specialityId;
    }

    public void setSpecialityId(String specialityId) {
        this.specialityId = specialityId;
    }

    public subject_group getSubjectGroup() {
        return subjectGroup;
    }

    public void setSubjectGroup(subject_group subjectGroup) {
        this.subjectGroup = subjectGroup;
    }

    public base_speciality getBaseSpeciality() {
        return baseSpeciality;
    }

    public void setBaseSpeciality(base_speciality baseSpeciality) {
        this.baseSpeciality = baseSpeciality;
    }

    public String getBack1() {
        return back1;
    }

    public void setBack1(String back1) {
        this.back1 = back1;
    }

    public String getBack2() {
        return back2;
    }

    public void setBack2(String back2) {
        this.back2 = back2;
    }

    public String getBack3() {
        return back3;
    }

    public void setBack3(String back3) {
        this.back3 = back3;
    }

    public String getJudgingCode() {
        return judgingCode;
    }

    public void setJudgingCode(String judgingCode) {
        this.judgingCode = judgingCode;
    }

    public speciality_group(Integer id, String groupId, String specialityId, subject_group subjectGroup, base_speciality baseSpeciality, String back1, String back2, String back3) {

        this.id = id;
        this.groupId = groupId;
        this.specialityId = specialityId;
        this.subjectGroup = subjectGroup;
        this.baseSpeciality = baseSpeciality;
        this.back1 = back1;
        this.back2 = back2;
        this.back3 = back3;
    }

    public speciality_group() {

    }
}