package com.hz.demo.model;

public class subject_group {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SUBJECT_GROUP.ID
     *
     * @mbg.generated Fri Sep 21 13:53:26 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SUBJECT_GROUP.JUDGING_CODE
     *
     * @mbg.generated Fri Sep 21 13:53:26 CST 2018
     */
    private String judgingCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SUBJECT_GROUP.GROUP_NO
     *
     * @mbg.generated Fri Sep 21 13:53:26 CST 2018
     */
    private String groupNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SUBJECT_GROUP.GROUP_NAME
     *
     * @mbg.generated Fri Sep 21 13:53:26 CST 2018
     */
    private String groupName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SUBJECT_GROUP.YEAR_NO
     *
     * @mbg.generated Fri Sep 21 13:53:26 CST 2018
     */
    private String yearNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SUBJECT_GROUP.BACK1
     *
     * @mbg.generated Fri Sep 21 13:53:26 CST 2018
     */
    private String back1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SUBJECT_GROUP.BACK2
     *
     * @mbg.generated Fri Sep 21 13:53:26 CST 2018
     */
    private String back2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_SUBJECT_GROUP.BACK3
     *
     * @mbg.generated Fri Sep 21 13:53:26 CST 2018
     */
    private String back3;

    private String groupLeader;

    private String professialId;

    private String professialName;

    private String proportion;

    @Override
    public String toString() {
        return "subject_group{" +
                "id=" + id +
                ", judgingCode='" + judgingCode + '\'' +
                ", groupNo='" + groupNo + '\'' +
                ", groupName='" + groupName + '\'' +
                ", yearNo='" + yearNo + '\'' +
                ", back1='" + back1 + '\'' +
                ", back2='" + back2 + '\'' +
                ", back3='" + back3 + '\'' +
                ", groupLeader='" + groupLeader + '\'' +
                ", professialId='" + professialId + '\'' +
                ", professialName='" + professialName + '\'' +
                ", proportion='" + proportion + '\'' +
                '}';
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getJudgingCode() {
        return judgingCode;
    }

    public void setJudgingCode(String judgingCode) {
        this.judgingCode = judgingCode;
    }

    public String getGroupNo() {
        return groupNo;
    }

    public void setGroupNo(String groupNo) {
        this.groupNo = groupNo;
    }

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public String getYearNo() {
        return yearNo;
    }

    public void setYearNo(String yearNo) {
        this.yearNo = yearNo;
    }

    public String getBack1() {
        return back1;
    }

    public void setBack1(String back1) {
        this.back1 = back1;
    }

    public String getBack2() {
        return back2;
    }

    public void setBack2(String back2) {
        this.back2 = back2;
    }

    public String getBack3() {
        return back3;
    }

    public void setBack3(String back3) {
        this.back3 = back3;
    }

    public String getGroupLeader() {
        return groupLeader;
    }

    public void setGroupLeader(String groupLeader) {
        this.groupLeader = groupLeader;
    }

    public String getProfessialId() {
        return professialId;
    }

    public void setProfessialId(String professialId) {
        this.professialId = professialId;
    }

    public String getProfessialName() {
        return professialName;
    }

    public void setProfessialName(String professialName) {
        this.professialName = professialName;
    }

    public String getProportion() {
        return proportion;
    }

    public void setProportion(String proportion) {
        this.proportion = proportion;
    }

    public subject_group(Integer id, String judgingCode, String groupNo, String groupName, String yearNo, String back1, String back2, String back3, String groupLeader, String professialId,String professialName,String proportion) {

        this.id = id;
        this.judgingCode = judgingCode;
        this.groupNo = groupNo;
        this.groupName = groupName;
        this.yearNo = yearNo;
        this.back1 = back1;
        this.back2 = back2;
        this.back3 = back3;
        this.groupLeader = groupLeader;
        this.professialId = professialId;
        this.professialName=professialName;
        this.proportion=proportion;
    }

    public subject_group() {
    }
}