package com.hz.demo.model;

public class sys_rolemenufun {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rolemenufun.role_menu_fun_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private String roleMenuFunId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rolemenufun.role_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_rolemenufun.menu_fun_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private String menuFunId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rolemenufun.role_menu_fun_id
     *
     * @return the value of sys_rolemenufun.role_menu_fun_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public String getRoleMenuFunId() {
        return roleMenuFunId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rolemenufun.role_menu_fun_id
     *
     * @param roleMenuFunId the value for sys_rolemenufun.role_menu_fun_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setRoleMenuFunId(String roleMenuFunId) {
        this.roleMenuFunId = roleMenuFunId == null ? null : roleMenuFunId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rolemenufun.role_id
     *
     * @return the value of sys_rolemenufun.role_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rolemenufun.role_id
     *
     * @param roleId the value for sys_rolemenufun.role_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_rolemenufun.menu_fun_id
     *
     * @return the value of sys_rolemenufun.menu_fun_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public String getMenuFunId() {
        return menuFunId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_rolemenufun.menu_fun_id
     *
     * @param menuFunId the value for sys_rolemenufun.menu_fun_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setMenuFunId(String menuFunId) {
        this.menuFunId = menuFunId == null ? null : menuFunId.trim();
    }
}