package com.hz.demo.model;

import java.math.BigDecimal;

public class sys_rolegroup {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLEGROUP.ID
     *
     * @mbg.generated Thu Sep 20 09:12:24 CST 2018
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLEGROUP.ROLE_GROUPCODE
     *
     * @mbg.generated Thu Sep 20 09:12:24 CST 2018
     */
    private String roleGroupcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLEGROUP.ROLE_GROUPNAME
     *
     * @mbg.generated Thu Sep 20 09:12:24 CST 2018
     */
    private String roleGroupname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLEGROUP.ROLEID
     *
     * @mbg.generated Thu Sep 20 09:12:24 CST 2018
     */
    private String roleid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLEGROUP.BACK1
     *
     * @mbg.generated Thu Sep 20 09:12:24 CST 2018
     */
    private String back1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLEGROUP.BACK2
     *
     * @mbg.generated Thu Sep 20 09:12:24 CST 2018
     */
    private String back2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_ROLEGROUP.BACK3
     *
     * @mbg.generated Thu Sep 20 09:12:24 CST 2018
     */
    private String back3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLEGROUP.ID
     *
     * @return the value of SYS_ROLEGROUP.ID
     *
     * @mbg.generated Thu Sep 20 09:12:24 CST 2018
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLEGROUP.ID
     *
     * @param id the value for SYS_ROLEGROUP.ID
     *
     * @mbg.generated Thu Sep 20 09:12:24 CST 2018
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLEGROUP.ROLE_GROUPCODE
     *
     * @return the value of SYS_ROLEGROUP.ROLE_GROUPCODE
     *
     * @mbg.generated Thu Sep 20 09:12:24 CST 2018
     */
    public String getRoleGroupcode() {
        return roleGroupcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLEGROUP.ROLE_GROUPCODE
     *
     * @param roleGroupcode the value for SYS_ROLEGROUP.ROLE_GROUPCODE
     *
     * @mbg.generated Thu Sep 20 09:12:24 CST 2018
     */
    public void setRoleGroupcode(String roleGroupcode) {
        this.roleGroupcode = roleGroupcode == null ? null : roleGroupcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLEGROUP.ROLE_GROUPNAME
     *
     * @return the value of SYS_ROLEGROUP.ROLE_GROUPNAME
     *
     * @mbg.generated Thu Sep 20 09:12:24 CST 2018
     */
    public String getRoleGroupname() {
        return roleGroupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLEGROUP.ROLE_GROUPNAME
     *
     * @param roleGroupname the value for SYS_ROLEGROUP.ROLE_GROUPNAME
     *
     * @mbg.generated Thu Sep 20 09:12:24 CST 2018
     */
    public void setRoleGroupname(String roleGroupname) {
        this.roleGroupname = roleGroupname == null ? null : roleGroupname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLEGROUP.ROLEID
     *
     * @return the value of SYS_ROLEGROUP.ROLEID
     *
     * @mbg.generated Thu Sep 20 09:12:24 CST 2018
     */
    public String getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLEGROUP.ROLEID
     *
     * @param roleid the value for SYS_ROLEGROUP.ROLEID
     *
     * @mbg.generated Thu Sep 20 09:12:24 CST 2018
     */
    public void setRoleid(String roleid) {
        this.roleid = roleid == null ? null : roleid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLEGROUP.BACK1
     *
     * @return the value of SYS_ROLEGROUP.BACK1
     *
     * @mbg.generated Thu Sep 20 09:12:24 CST 2018
     */
    public String getBack1() {
        return back1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLEGROUP.BACK1
     *
     * @param back1 the value for SYS_ROLEGROUP.BACK1
     *
     * @mbg.generated Thu Sep 20 09:12:24 CST 2018
     */
    public void setBack1(String back1) {
        this.back1 = back1 == null ? null : back1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLEGROUP.BACK2
     *
     * @return the value of SYS_ROLEGROUP.BACK2
     *
     * @mbg.generated Thu Sep 20 09:12:24 CST 2018
     */
    public String getBack2() {
        return back2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLEGROUP.BACK2
     *
     * @param back2 the value for SYS_ROLEGROUP.BACK2
     *
     * @mbg.generated Thu Sep 20 09:12:24 CST 2018
     */
    public void setBack2(String back2) {
        this.back2 = back2 == null ? null : back2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_ROLEGROUP.BACK3
     *
     * @return the value of SYS_ROLEGROUP.BACK3
     *
     * @mbg.generated Thu Sep 20 09:12:24 CST 2018
     */
    public String getBack3() {
        return back3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_ROLEGROUP.BACK3
     *
     * @param back3 the value for SYS_ROLEGROUP.BACK3
     *
     * @mbg.generated Thu Sep 20 09:12:24 CST 2018
     */
    public void setBack3(String back3) {
        this.back3 = back3 == null ? null : back3.trim();
    }
}