package com.hz.demo.model;

public class sys_menufun {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menufun.menu_fun_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private String menuFunId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menufun.menu_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private String menuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_menufun.fun_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private String btnCode;
    private String btnName;
    private Integer state;
    private Integer fsort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menufun.menu_fun_id
     *
     * @return the value of sys_menufun.menu_fun_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public String getMenuFunId() {
        return menuFunId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menufun.menu_fun_id
     *
     * @param menuFunId the value for sys_menufun.menu_fun_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setMenuFunId(String menuFunId) {
        this.menuFunId = menuFunId == null ? null : menuFunId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_menufun.menu_id
     *
     * @return the value of sys_menufun.menu_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public String getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_menufun.menu_id
     *
     * @param menuId the value for sys_menufun.menu_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setMenuId(String menuId) {
        this.menuId = menuId == null ? null : menuId.trim();
    }

    public String getBtnCode() {
        return btnCode;
    }

    public void setBtnCode(String btnCode) {
        this.btnCode = btnCode == null ? null : btnCode.trim();
    }

    public String getBtnName() {
        return btnName;
    }

    public void setBtnName(String btnName) {
        this.btnName = btnName == null ? null : btnName.trim();
    }

    public Integer getState() {
        return state;
    }

    public void setState(Integer state) {
        this.state = state;
    }

    public Integer getFsort() {
        return fsort;
    }

    public void setFsort(Integer fsort) {
        this.fsort = fsort;
    }
}