package com.hz.demo.model;

public class sys_userrole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_userrole.user_role_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private String userRoleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_userrole.user_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_userrole.role_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private String roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_userrole.user_role_id
     *
     * @return the value of sys_userrole.user_role_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public String getUserRoleId() {
        return userRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_userrole.user_role_id
     *
     * @param userRoleId the value for sys_userrole.user_role_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setUserRoleId(String userRoleId) {
        this.userRoleId = userRoleId == null ? null : userRoleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_userrole.user_id
     *
     * @return the value of sys_userrole.user_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_userrole.user_id
     *
     * @param userId the value for sys_userrole.user_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_userrole.role_id
     *
     * @return the value of sys_userrole.role_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_userrole.role_id
     *
     * @param roleId the value for sys_userrole.role_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }
}