package com.hz.demo.model;

import java.util.Date;

public class sys_role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.role_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private String roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.role_name
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.fsort
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private Integer fsort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.add_user_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private String addUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.add_time
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.state
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.backup1
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private String backup1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.backup2
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private String backup2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.backup3
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private String backup3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.role_id
     *
     * @return the value of sys_role.role_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.role_id
     *
     * @param roleId the value for sys_role.role_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.role_name
     *
     * @return the value of sys_role.role_name
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.role_name
     *
     * @param roleName the value for sys_role.role_name
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.fsort
     *
     * @return the value of sys_role.fsort
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public Integer getFsort() {
        return fsort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.fsort
     *
     * @param fsort the value for sys_role.fsort
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setFsort(Integer fsort) {
        this.fsort = fsort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.add_user_id
     *
     * @return the value of sys_role.add_user_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public String getAddUserId() {
        return addUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.add_user_id
     *
     * @param addUserId the value for sys_role.add_user_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setAddUserId(String addUserId) {
        this.addUserId = addUserId == null ? null : addUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.add_time
     *
     * @return the value of sys_role.add_time
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.add_time
     *
     * @param addTime the value for sys_role.add_time
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.state
     *
     * @return the value of sys_role.state
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.state
     *
     * @param state the value for sys_role.state
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.backup1
     *
     * @return the value of sys_role.backup1
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public String getBackup1() {
        return backup1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.backup1
     *
     * @param backup1 the value for sys_role.backup1
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setBackup1(String backup1) {
        this.backup1 = backup1 == null ? null : backup1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.backup2
     *
     * @return the value of sys_role.backup2
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public String getBackup2() {
        return backup2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.backup2
     *
     * @param backup2 the value for sys_role.backup2
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setBackup2(String backup2) {
        this.backup2 = backup2 == null ? null : backup2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.backup3
     *
     * @return the value of sys_role.backup3
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public String getBackup3() {
        return backup3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.backup3
     *
     * @param backup3 the value for sys_role.backup3
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setBackup3(String backup3) {
        this.backup3 = backup3 == null ? null : backup3.trim();
    }
}