package com.hz.demo.model;

import java.util.Date;

public class sys_token {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_token.to_ken_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private String toKenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_token.user_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_token.create_date
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_token.invalid_date
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private Date invalidDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_token.state
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_token.to_ken_id
     *
     * @return the value of sys_token.to_ken_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public String getToKenId() {
        return toKenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_token.to_ken_id
     *
     * @param toKenId the value for sys_token.to_ken_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setToKenId(String toKenId) {
        this.toKenId = toKenId == null ? null : toKenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_token.user_id
     *
     * @return the value of sys_token.user_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_token.user_id
     *
     * @param userId the value for sys_token.user_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_token.create_date
     *
     * @return the value of sys_token.create_date
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_token.create_date
     *
     * @param createDate the value for sys_token.create_date
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_token.invalid_date
     *
     * @return the value of sys_token.invalid_date
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public Date getInvalidDate() {
        return invalidDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_token.invalid_date
     *
     * @param invalidDate the value for sys_token.invalid_date
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setInvalidDate(Date invalidDate) {
        this.invalidDate = invalidDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_token.state
     *
     * @return the value of sys_token.state
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_token.state
     *
     * @param state the value for sys_token.state
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }
}