package com.hz.demo.model;

import java.util.Date;

public class sys_log {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.log_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private String logId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.ip
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.page
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private String page;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.message
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.add_user_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private String addUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.add_time
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.backup1
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private String backup1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.backup2
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private String backup2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_log.backup3
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private String backup3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.log_id
     *
     * @return the value of sys_log.log_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public String getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.log_id
     *
     * @param logId the value for sys_log.log_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setLogId(String logId) {
        this.logId = logId == null ? null : logId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.ip
     *
     * @return the value of sys_log.ip
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.ip
     *
     * @param ip the value for sys_log.ip
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.page
     *
     * @return the value of sys_log.page
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public String getPage() {
        return page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.page
     *
     * @param page the value for sys_log.page
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setPage(String page) {
        this.page = page == null ? null : page.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.message
     *
     * @return the value of sys_log.message
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.message
     *
     * @param message the value for sys_log.message
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.add_user_id
     *
     * @return the value of sys_log.add_user_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public String getAddUserId() {
        return addUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.add_user_id
     *
     * @param addUserId the value for sys_log.add_user_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setAddUserId(String addUserId) {
        this.addUserId = addUserId == null ? null : addUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.add_time
     *
     * @return the value of sys_log.add_time
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.add_time
     *
     * @param addTime the value for sys_log.add_time
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.backup1
     *
     * @return the value of sys_log.backup1
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public String getBackup1() {
        return backup1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.backup1
     *
     * @param backup1 the value for sys_log.backup1
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setBackup1(String backup1) {
        this.backup1 = backup1 == null ? null : backup1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.backup2
     *
     * @return the value of sys_log.backup2
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public String getBackup2() {
        return backup2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.backup2
     *
     * @param backup2 the value for sys_log.backup2
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setBackup2(String backup2) {
        this.backup2 = backup2 == null ? null : backup2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_log.backup3
     *
     * @return the value of sys_log.backup3
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public String getBackup3() {
        return backup3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_log.backup3
     *
     * @param backup3 the value for sys_log.backup3
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setBackup3(String backup3) {
        this.backup3 = backup3 == null ? null : backup3.trim();
    }
}