package com.hz.demo.model;

import java.util.Date;

public class sys_user {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private String userId;

    private Integer userType;


    private String unitCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.display_name
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private String displayName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.login_name
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.password
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.sex
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.mobilephone
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private String mobilephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.email
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.id_card_no
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private String idCardNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.address
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.add_user_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private String addUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.add_time
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.state
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_themes
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private String userThemes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.headportrait_img
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private String headportraitImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.backup1
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private String backup1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.backup2
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private String backup2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.backup3
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    private String backup3;

    private String judgingCode;
    private String specialityId;
    private String judgingName;

    public String getJudgingName() {
        return judgingName;
    }

    public void setJudgingName(String judgingName) {
        this.judgingName = judgingName;
    }

    public String getSpecialityId() {
        return specialityId;
    }

    public void setSpecialityId(String specialityId) {
        this.specialityId = specialityId;
    }

    public Integer getUserType() {
        return userType;
    }

    public void setUserType(Integer userType) {
        this.userType = userType;
    }
    public String getJudgingCode() {
        return judgingCode;
    }

    public void setJudgingCode(String judgingCode) {
        this.judgingCode = judgingCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_id
     *
     * @return the value of sys_user.user_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */



    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_id
     *
     * @param userId the value for sys_user.user_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }


    public String getUnitCode() {
        return unitCode;
    }


    public void setUnitCode(String unitCode) {
        this.unitCode = unitCode == null ? null : unitCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.display_name
     *
     * @return the value of sys_user.display_name
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public String getDisplayName() {
        return displayName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.display_name
     *
     * @param displayName the value for sys_user.display_name
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setDisplayName(String displayName) {
        this.displayName = displayName == null ? null : displayName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.login_name
     *
     * @return the value of sys_user.login_name
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.login_name
     *
     * @param loginName the value for sys_user.login_name
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.password
     *
     * @return the value of sys_user.password
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.password
     *
     * @param password the value for sys_user.password
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.sex
     *
     * @return the value of sys_user.sex
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.sex
     *
     * @param sex the value for sys_user.sex
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.mobilephone
     *
     * @return the value of sys_user.mobilephone
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public String getMobilephone() {
        return mobilephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.mobilephone
     *
     * @param mobilephone the value for sys_user.mobilephone
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setMobilephone(String mobilephone) {
        this.mobilephone = mobilephone == null ? null : mobilephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.email
     *
     * @return the value of sys_user.email
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.email
     *
     * @param email the value for sys_user.email
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.id_card_no
     *
     * @return the value of sys_user.id_card_no
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public String getIdCardNo() {
        return idCardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.id_card_no
     *
     * @param idCardNo the value for sys_user.id_card_no
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setIdCardNo(String idCardNo) {
        this.idCardNo = idCardNo == null ? null : idCardNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.address
     *
     * @return the value of sys_user.address
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.address
     *
     * @param address the value for sys_user.address
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.add_user_id
     *
     * @return the value of sys_user.add_user_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public String getAddUserId() {
        return addUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.add_user_id
     *
     * @param addUserId the value for sys_user.add_user_id
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setAddUserId(String addUserId) {
        this.addUserId = addUserId == null ? null : addUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.add_time
     *
     * @return the value of sys_user.add_time
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public Date getAddTime() {
        return addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.add_time
     *
     * @param addTime the value for sys_user.add_time
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setAddTime(Date addTime) {
        this.addTime = addTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.state
     *
     * @return the value of sys_user.state
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.state
     *
     * @param state the value for sys_user.state
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_themes
     *
     * @return the value of sys_user.user_themes
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public String getUserThemes() {
        return userThemes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_themes
     *
     * @param userThemes the value for sys_user.user_themes
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setUserThemes(String userThemes) {
        this.userThemes = userThemes == null ? null : userThemes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.headportrait_img
     *
     * @return the value of sys_user.headportrait_img
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public String getHeadportraitImg() {
        return headportraitImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.headportrait_img
     *
     * @param headportraitImg the value for sys_user.headportrait_img
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setHeadportraitImg(String headportraitImg) {
        this.headportraitImg = headportraitImg == null ? null : headportraitImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.backup1
     *
     * @return the value of sys_user.backup1
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public String getBackup1() {
        return backup1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.backup1
     *
     * @param backup1 the value for sys_user.backup1
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setBackup1(String backup1) {
        this.backup1 = backup1 == null ? null : backup1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.backup2
     *
     * @return the value of sys_user.backup2
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public String getBackup2() {
        return backup2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.backup2
     *
     * @param backup2 the value for sys_user.backup2
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setBackup2(String backup2) {
        this.backup2 = backup2 == null ? null : backup2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.backup3
     *
     * @return the value of sys_user.backup3
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public String getBackup3() {
        return backup3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.backup3
     *
     * @param backup3 the value for sys_user.backup3
     *
     * @mbg.generated Tue May 08 09:26:48 CST 2018
     */
    public void setBackup3(String backup3) {
        this.backup3 = backup3 == null ? null : backup3.trim();
    }
}