package com.hz.demo.model;

import java.math.BigDecimal;
import java.util.Date;

public class SysArea {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_AREA.ID
     *
     * @mbg.generated Thu Sep 06 08:55:34 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_AREA.AREA_CODE
     *
     * @mbg.generated Thu Sep 06 08:55:34 CST 2018
     */
    private String areaCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_AREA.AREA_PARENTCODE
     *
     * @mbg.generated Thu Sep 06 08:55:34 CST 2018
     */
    private String areaParentcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_AREA.AREA_NAME
     *
     * @mbg.generated Thu Sep 06 08:55:34 CST 2018
     */
    private String areaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_AREA.AREA_GRADE
     *
     * @mbg.generated Thu Sep 06 08:55:34 CST 2018
     */
    private String areaGrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_AREA.FSORT
     *
     * @mbg.generated Thu Sep 06 08:55:34 CST 2018
     */
    private BigDecimal fsort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_AREA.ADDTIME
     *
     * @mbg.generated Thu Sep 06 08:55:34 CST 2018
     */
    private Date addtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_AREA.ADDUSERID
     *
     * @mbg.generated Thu Sep 06 08:55:34 CST 2018
     */
    private String adduserid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_AREA.STATE
     *
     * @mbg.generated Thu Sep 06 08:55:34 CST 2018
     */
    private BigDecimal state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_AREA.BACK1
     *
     * @mbg.generated Thu Sep 06 08:55:34 CST 2018
     */
    private String back1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_AREA.BACK2
     *
     * @mbg.generated Thu Sep 06 08:55:34 CST 2018
     */
    private String back2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SYS_AREA.BACK3
     *
     * @mbg.generated Thu Sep 06 08:55:34 CST 2018
     */
    private String back3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_AREA.ID
     *
     * @return the value of SYS_AREA.ID
     *
     * @mbg.generated Thu Sep 06 08:55:34 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_AREA.ID
     *
     * @param id the value for SYS_AREA.ID
     *
     * @mbg.generated Thu Sep 06 08:55:34 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_AREA.AREA_CODE
     *
     * @return the value of SYS_AREA.AREA_CODE
     *
     * @mbg.generated Thu Sep 06 08:55:34 CST 2018
     */
    public String getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_AREA.AREA_CODE
     *
     * @param areaCode the value for SYS_AREA.AREA_CODE
     *
     * @mbg.generated Thu Sep 06 08:55:34 CST 2018
     */
    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode == null ? null : areaCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_AREA.AREA_PARENTCODE
     *
     * @return the value of SYS_AREA.AREA_PARENTCODE
     *
     * @mbg.generated Thu Sep 06 08:55:34 CST 2018
     */
    public String getAreaParentcode() {
        return areaParentcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_AREA.AREA_PARENTCODE
     *
     * @param areaParentcode the value for SYS_AREA.AREA_PARENTCODE
     *
     * @mbg.generated Thu Sep 06 08:55:34 CST 2018
     */
    public void setAreaParentcode(String areaParentcode) {
        this.areaParentcode = areaParentcode == null ? null : areaParentcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_AREA.AREA_NAME
     *
     * @return the value of SYS_AREA.AREA_NAME
     *
     * @mbg.generated Thu Sep 06 08:55:34 CST 2018
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_AREA.AREA_NAME
     *
     * @param areaName the value for SYS_AREA.AREA_NAME
     *
     * @mbg.generated Thu Sep 06 08:55:34 CST 2018
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_AREA.AREA_GRADE
     *
     * @return the value of SYS_AREA.AREA_GRADE
     *
     * @mbg.generated Thu Sep 06 08:55:34 CST 2018
     */
    public String getAreaGrade() {
        return areaGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_AREA.AREA_GRADE
     *
     * @param areaGrade the value for SYS_AREA.AREA_GRADE
     *
     * @mbg.generated Thu Sep 06 08:55:34 CST 2018
     */
    public void setAreaGrade(String areaGrade) {
        this.areaGrade = areaGrade == null ? null : areaGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_AREA.FSORT
     *
     * @return the value of SYS_AREA.FSORT
     *
     * @mbg.generated Thu Sep 06 08:55:34 CST 2018
     */
    public BigDecimal getFsort() {
        return fsort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_AREA.FSORT
     *
     * @param fsort the value for SYS_AREA.FSORT
     *
     * @mbg.generated Thu Sep 06 08:55:34 CST 2018
     */
    public void setFsort(BigDecimal fsort) {
        this.fsort = fsort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_AREA.ADDTIME
     *
     * @return the value of SYS_AREA.ADDTIME
     *
     * @mbg.generated Thu Sep 06 08:55:34 CST 2018
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_AREA.ADDTIME
     *
     * @param addtime the value for SYS_AREA.ADDTIME
     *
     * @mbg.generated Thu Sep 06 08:55:34 CST 2018
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_AREA.ADDUSERID
     *
     * @return the value of SYS_AREA.ADDUSERID
     *
     * @mbg.generated Thu Sep 06 08:55:34 CST 2018
     */
    public String getAdduserid() {
        return adduserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_AREA.ADDUSERID
     *
     * @param adduserid the value for SYS_AREA.ADDUSERID
     *
     * @mbg.generated Thu Sep 06 08:55:34 CST 2018
     */
    public void setAdduserid(String adduserid) {
        this.adduserid = adduserid == null ? null : adduserid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_AREA.STATE
     *
     * @return the value of SYS_AREA.STATE
     *
     * @mbg.generated Thu Sep 06 08:55:34 CST 2018
     */
    public BigDecimal getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_AREA.STATE
     *
     * @param state the value for SYS_AREA.STATE
     *
     * @mbg.generated Thu Sep 06 08:55:34 CST 2018
     */
    public void setState(BigDecimal state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_AREA.BACK1
     *
     * @return the value of SYS_AREA.BACK1
     *
     * @mbg.generated Thu Sep 06 08:55:34 CST 2018
     */
    public String getBack1() {
        return back1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_AREA.BACK1
     *
     * @param back1 the value for SYS_AREA.BACK1
     *
     * @mbg.generated Thu Sep 06 08:55:34 CST 2018
     */
    public void setBack1(String back1) {
        this.back1 = back1 == null ? null : back1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_AREA.BACK2
     *
     * @return the value of SYS_AREA.BACK2
     *
     * @mbg.generated Thu Sep 06 08:55:34 CST 2018
     */
    public String getBack2() {
        return back2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_AREA.BACK2
     *
     * @param back2 the value for SYS_AREA.BACK2
     *
     * @mbg.generated Thu Sep 06 08:55:34 CST 2018
     */
    public void setBack2(String back2) {
        this.back2 = back2 == null ? null : back2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SYS_AREA.BACK3
     *
     * @return the value of SYS_AREA.BACK3
     *
     * @mbg.generated Thu Sep 06 08:55:34 CST 2018
     */
    public String getBack3() {
        return back3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SYS_AREA.BACK3
     *
     * @param back3 the value for SYS_AREA.BACK3
     *
     * @mbg.generated Thu Sep 06 08:55:34 CST 2018
     */
    public void setBack3(String back3) {
        this.back3 = back3 == null ? null : back3.trim();
    }
}