package com.hz.demo.model;

import java.math.BigDecimal;

public class Titles {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_PARAM_POSITIONALTITLE.ID
     *
     * @mbg.generated Tue Sep 18 10:40:47 CST 2018
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_PARAM_POSITIONALTITLE.QUALIFICATION_CODE
     *
     * @mbg.generated Tue Sep 18 10:40:47 CST 2018
     */
    private String qualificationCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_PARAM_POSITIONALTITLE.QUALIFICATION_NAME
     *
     * @mbg.generated Tue Sep 18 10:40:47 CST 2018
     */
    private String qualificationName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_PARAM_POSITIONALTITLE.IS_REVIEW
     *
     * @mbg.generated Tue Sep 18 10:40:47 CST 2018
     */
    private BigDecimal isReview;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_PARAM_POSITIONALTITLE.IS_FIRMLY_BELIEVE
     *
     * @mbg.generated Tue Sep 18 10:40:47 CST 2018
     */
    private BigDecimal isFirmlyBelieve;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_PARAM_POSITIONALTITLE.BACK1
     *
     * @mbg.generated Tue Sep 18 10:40:47 CST 2018
     */
    private String back1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_PARAM_POSITIONALTITLE.BACK2
     *
     * @mbg.generated Tue Sep 18 10:40:47 CST 2018
     */
    private String back2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASE_PARAM_POSITIONALTITLE.BACK3
     *
     * @mbg.generated Tue Sep 18 10:40:47 CST 2018
     */
    private String back3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_PARAM_POSITIONALTITLE.ID
     *
     * @return the value of BASE_PARAM_POSITIONALTITLE.ID
     *
     * @mbg.generated Tue Sep 18 10:40:47 CST 2018
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_PARAM_POSITIONALTITLE.ID
     *
     * @param id the value for BASE_PARAM_POSITIONALTITLE.ID
     *
     * @mbg.generated Tue Sep 18 10:40:47 CST 2018
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_PARAM_POSITIONALTITLE.QUALIFICATION_CODE
     *
     * @return the value of BASE_PARAM_POSITIONALTITLE.QUALIFICATION_CODE
     *
     * @mbg.generated Tue Sep 18 10:40:47 CST 2018
     */
    public String getQualificationCode() {
        return qualificationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_PARAM_POSITIONALTITLE.QUALIFICATION_CODE
     *
     * @param qualificationCode the value for BASE_PARAM_POSITIONALTITLE.QUALIFICATION_CODE
     *
     * @mbg.generated Tue Sep 18 10:40:47 CST 2018
     */
    public void setQualificationCode(String qualificationCode) {
        this.qualificationCode = qualificationCode == null ? null : qualificationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_PARAM_POSITIONALTITLE.QUALIFICATION_NAME
     *
     * @return the value of BASE_PARAM_POSITIONALTITLE.QUALIFICATION_NAME
     *
     * @mbg.generated Tue Sep 18 10:40:47 CST 2018
     */
    public String getQualificationName() {
        return qualificationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_PARAM_POSITIONALTITLE.QUALIFICATION_NAME
     *
     * @param qualificationName the value for BASE_PARAM_POSITIONALTITLE.QUALIFICATION_NAME
     *
     * @mbg.generated Tue Sep 18 10:40:47 CST 2018
     */
    public void setQualificationName(String qualificationName) {
        this.qualificationName = qualificationName == null ? null : qualificationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_PARAM_POSITIONALTITLE.IS_REVIEW
     *
     * @return the value of BASE_PARAM_POSITIONALTITLE.IS_REVIEW
     *
     * @mbg.generated Tue Sep 18 10:40:47 CST 2018
     */
    public BigDecimal getIsReview() {
        return isReview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_PARAM_POSITIONALTITLE.IS_REVIEW
     *
     * @param isReview the value for BASE_PARAM_POSITIONALTITLE.IS_REVIEW
     *
     * @mbg.generated Tue Sep 18 10:40:47 CST 2018
     */
    public void setIsReview(BigDecimal isReview) {
        this.isReview = isReview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_PARAM_POSITIONALTITLE.IS_FIRMLY_BELIEVE
     *
     * @return the value of BASE_PARAM_POSITIONALTITLE.IS_FIRMLY_BELIEVE
     *
     * @mbg.generated Tue Sep 18 10:40:47 CST 2018
     */
    public BigDecimal getIsFirmlyBelieve() {
        return isFirmlyBelieve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_PARAM_POSITIONALTITLE.IS_FIRMLY_BELIEVE
     *
     * @param isFirmlyBelieve the value for BASE_PARAM_POSITIONALTITLE.IS_FIRMLY_BELIEVE
     *
     * @mbg.generated Tue Sep 18 10:40:47 CST 2018
     */
    public void setIsFirmlyBelieve(BigDecimal isFirmlyBelieve) {
        this.isFirmlyBelieve = isFirmlyBelieve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_PARAM_POSITIONALTITLE.BACK1
     *
     * @return the value of BASE_PARAM_POSITIONALTITLE.BACK1
     *
     * @mbg.generated Tue Sep 18 10:40:47 CST 2018
     */
    public String getBack1() {
        return back1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_PARAM_POSITIONALTITLE.BACK1
     *
     * @param back1 the value for BASE_PARAM_POSITIONALTITLE.BACK1
     *
     * @mbg.generated Tue Sep 18 10:40:47 CST 2018
     */
    public void setBack1(String back1) {
        this.back1 = back1 == null ? null : back1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_PARAM_POSITIONALTITLE.BACK2
     *
     * @return the value of BASE_PARAM_POSITIONALTITLE.BACK2
     *
     * @mbg.generated Tue Sep 18 10:40:47 CST 2018
     */
    public String getBack2() {
        return back2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_PARAM_POSITIONALTITLE.BACK2
     *
     * @param back2 the value for BASE_PARAM_POSITIONALTITLE.BACK2
     *
     * @mbg.generated Tue Sep 18 10:40:47 CST 2018
     */
    public void setBack2(String back2) {
        this.back2 = back2 == null ? null : back2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASE_PARAM_POSITIONALTITLE.BACK3
     *
     * @return the value of BASE_PARAM_POSITIONALTITLE.BACK3
     *
     * @mbg.generated Tue Sep 18 10:40:47 CST 2018
     */
    public String getBack3() {
        return back3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASE_PARAM_POSITIONALTITLE.BACK3
     *
     * @param back3 the value for BASE_PARAM_POSITIONALTITLE.BACK3
     *
     * @mbg.generated Tue Sep 18 10:40:47 CST 2018
     */
    public void setBack3(String back3) {
        this.back3 = back3 == null ? null : back3.trim();
    }
}